const questions = [
  // Bloque Inicial Corregido
  {text:"¿En qué año comenzó la Primera Guerra Mundial?", options:["1492", "1776", "1914", "1945"], correct:2},
  {text:"¿Qué planeta es conocido como el planeta anillado?", options:["Marte", "Júpiter", "Venus", "Saturno"], correct:3},
  {text:"¿Qué país ganó el mundial de fútbol en 1998?", options:["Brasil", "Alemania", "Italia", "Francia"], correct:3},
  {text:"Capital de Egipto", options:["Roma", "El Cairo", "Madrid", "Lisboa"], correct:1},
  {text:"¿Qué instrumento musical tiene viento?", options:["Guitarra", "Piano", "Violín", "Flauta"], correct:3},
  {text:"¿Qué instrumento musical tiene teclas?", options:["Guitarra", "Piano", "Violín", "Flauta"], correct:1},
  {text:"Capital de México", options:["Roma", "Ciudad de México", "Madrid", "Lisboa"], correct:1},
  {text:"¿En qué año terminó la Segunda Guerra Mundial?", options:["1492", "1776", "1914", "1945"], correct:3},
  {text:"¿Quién escribió Hamlet?", options:["Cervantes", "Shakespeare", "Gabriel García Márquez", "Homero"], correct:1},
  {text:"¿Qué país ganó el mundial de fútbol en 2018?", options:["Brasil", "Alemania", "Italia", "Francia"], correct:3},
  {text:"¿Qué planeta es conocido como el planeta gigante?", options:["Marte", "Júpiter", "Venus", "Saturno"], correct:1},
  {text:"¿Qué planeta es conocido como el planeta rojo?", options:["Marte", "Júpiter", "Venus", "Saturno"], correct:0},
  {text:"Capital de Argentina", options:["Roma", "Buenos Aires", "Madrid", "Lisboa"], correct:1},
  {text:"Capital de España", options:["Roma", "París", "Madrid", "Lisboa"], correct:2},
  {text:"Capital de Canadá", options:["Roma", "Ottawa", "Madrid", "Lisboa"], correct:1},
  {text:"¿Quién escribió Cien Años de Soledad?", options:["Cervantes", "Shakespeare", "Gabriel García Márquez", "Homero"], correct:2},
  {text:"¿En qué año se descubrió América?", options:["1492", "1776", "1914", "1945"], correct:0},
  {text:"¿Quién escribió Don Quijote?", options:["Cervantes", "Shakespeare", "Gabriel García Márquez", "Homero"], correct:0},
  {text:"¿Cuál es la montaña más alta del mundo?", options:["Everest", "K2", "Aconcagua", "Kilimanjaro"], correct:0},
  {text:"¿Qué país ganó el mundial de fútbol en 1970?", options:["Brasil", "Alemania", "Italia", "Francia"], correct:0},
  {text:"¿En qué continente está Italia?", options:["Europa", "Asia", "África", "América"], correct:0},
  {text:"¿En qué continente está Japón?", options:["Europa", "Asia", "África", "América"], correct:1},
  {text:"¿En qué continente está Francia?", options:["Europa", "Asia", "África", "América"], correct:0},
  {text:"¿Cuál es el elemento químico con símbolo H?", options:["Hidrógeno", "Oxígeno", "Carbono", "Helio"], correct:0},
  {text:"¿Cuál es el animal más grande?", options:["Elefante", "Ballena Azul", "Tiburón", "Águila"], correct:1},
  {text:"¿Quién escribió La Odisea?", options:["Cervantes", "Shakespeare", "Gabriel García Márquez", "Homero"], correct:3},
  {text:"¿En qué año comenzó la Independencia de Estados Unidos?", options:["1492", "1776", "1914", "1945"], correct:1},
  {text:"¿Cuál es el elemento químico con símbolo O?", options:["Hidrógeno", "Oxígeno", "Carbono", "Helio"], correct:1},
  {text:"¿Cuál es el animal más alto?", options:["Elefante", "Jirafa", "Tiburón", "Águila"], correct:1},
  {text:"¿Cuál es el animal más pesado?", options:["Elefante", "Ballena Azul", "Tiburón", "Águila"], correct:1},
  {text:"¿En qué continente está Canadá?", options:["Europa", "Asia", "África", "América"], correct:3},
  {text:"¿En qué continente está España?", options:["Europa", "Asia", "África", "América"], correct:0},
  {text:"¿Cuál es el elemento químico con símbolo He?", options:["Hidrógeno", "Oxígeno", "Carbono", "Helio"], correct:3},
  {text:"¿En qué continente está México?", options:["Europa", "Asia", "África", "América"], correct:3},
  {text:"¿Qué instrumento musical tiene cuerdas?", options:["Guitarra", "Piano", "Violín", "Flauta"], correct:0},
  {text:"¿Qué instrumento musical tiene arco?", options:["Guitarra", "Piano", "Violín", "Flauta"], correct:2},
  {text:"¿Qué país ganó el mundial de fútbol en 1958?", options:["Brasil", "Alemania", "Italia", "Francia"], correct:0},
  {text:"¿En qué continente está Egipto?", options:["Europa", "Asia", "África", "América"], correct:2},
  {text:"¿Cuál es el animal más rápido?", options:["Elefante", "Guepardo", "Tiburón", "Águila"], correct:1},
  {text:"¿Cuál es el elemento químico con símbolo C?", options:["Hidrógeno", "Oxígeno", "Carbono", "Helio"], correct:2},
  {text:"¿Qué planeta es conocido como el planeta gemelo de la Tierra?", options:["Marte", "Júpiter", "Venus", "Saturno"], correct:2},
  {text:"Capital de Francia", options:["Roma", "París", "Madrid", "Lisboa"], correct:1},
  {text:"Capital de China", options:["Roma", "Pekín", "Madrid", "Lisboa"], correct:1},
  {text:"¿En qué continente está Chile?", options:["Europa", "Asia", "África", "América"], correct:3},
  {text:"Capital de Italia", options:["Roma", "París", "Madrid", "Lisboa"], correct:0},
  {text:"Capital de Japón", options:["Roma", "Tokio", "Madrid", "Lisboa"], correct:1},
  {text:"Capital de Chile", options:["Roma", "Santiago", "Madrid", "Lisboa"], correct:1},
  {text:"¿En qué continente está Argentina?", options:["Europa", "Asia", "África", "América"], correct:3},

  // Nuevas Preguntas Agregadas (Corregidas)
  // Geografía
  {text:"¿Cuál es la capital de Australia?", options:["Sídney", "Melbourne", "Canberra", "Brisbane"], correct:2},
  {text:"¿Cuál es el océano más grande del mundo?", options:["Atlántico", "Índico", "Ártico", "Pacífico"], correct:3},
  {text:"¿En qué país se encuentra el Taj Mahal?", options:["China", "India", "Pakistán", "Nepal"], correct:1},
  {text:"¿Cuál es el río más largo del mundo?", options:["Nilo", "Amazonas", "Yangtsé", "Misisipi"], correct:1},
  {text:"¿Cuál es la capital de Rusia?", options:["San Petersburgo", "Moscú", "Kiev", "Varsovia"], correct:1},
  {text:"¿En qué continente se encuentra el desierto del Sahara?", options:["Asia", "Sudamérica", "África", "Australia"], correct:2},
  {text:"¿Cuál es la capital de Alemania?", options:["Múnich", "Hamburgo", "Berlín", "Frankfurt"], correct:2},
  {text:"¿Cuál es la montaña más alta de África?", options:["Monte Kenia", "Monte Stanley", "Monte Kilimanjaro", "Ras Dashen"], correct:2},
  {text:"¿Qué país es conocido como la 'Tierra del Sol Naciente'?", options:["China", "Corea del Sur", "Tailandia", "Japón"], correct:3},
  {text:"¿Cuál es la capital de Brasil?", options:["Río de Janeiro", "São Paulo", "Salvador", "Brasilia"], correct:3},
  {text:"¿En qué país se encuentran las ruinas de Machu Picchu?", options:["Colombia", "Ecuador", "Perú", "Bolivia"], correct:2},
  {text:"¿Cuál es el lago más grande de África?", options:["Lago Tanganica", "Lago Malaui", "Lago Victoria", "Lago Chad"], correct:2},
  {text:"¿Cuál es la capital de Portugal?", options:["Oporto", "Lisboa", "Faro", "Coímbra"], correct:1},
  {text:"¿Qué ciudad es famosa por sus canales?", options:["Ámsterdam", "Brujas", "Estocolmo", "Venecia"], correct:3},
  {text:"¿Cuál es el país más grande del mundo por área territorial?", options:["Canadá", "China", "Estados Unidos", "Rusia"], correct:3},
  {text:"¿En qué cordillera se encuentra el Aconcagua?", options:["Himalaya", "Alpes", "Andes", "Montañas Rocosas"], correct:2},
  {text:"Capital de Tailandia", options:["Hanoi", "Bangkok", "Manila", "Yakarta"], correct:1},
  {text:"¿Cuál es el desierto más grande del mundo?", options:["Sahara", "Gobi", "Kalahari", "Antártico"], correct:3},
  {text:"¿En qué país se encuentra la ciudad de Petra?", options:["Egipto", "Israel", "Siria", "Jordania"], correct:3},
  {text:"Capital de Corea del Sur", options:["Pionyang", "Seúl", "Busan", "Incheon"], correct:1},
  {text:"¿Qué estrecho separa Asia de América?", options:["Estrecho de Gibraltar", "Estrecho de Magallanes", "Estrecho de Bering", "Canal de Suez"], correct:2},
  {text:"Capital de Sudáfrica (administrativa)", options:["Ciudad del Cabo", "Johannesburgo", "Pretoria", "Durban"], correct:2},
  {text:"¿En qué país está el Monte Fuji?", options:["China", "Japón", "Corea", "Vietnam"], correct:1},
  {text:"¿Cuál es el lago más profundo del mundo?", options:["Lago Superior", "Lago Tanganica", "Lago Baikal", "Mar Caspio"], correct:2},
  {text:"Capital de Turquía", options:["Estambul", "Ankara", "Esmirna", "Bursa"], correct:1},
  {text:"¿Qué río pasa por París?", options:["Rin", "Loira", "Sena", "Tíber"], correct:2},
  {text:"¿Cuál es el país más poblado del mundo?", options:["India", "Estados Unidos", "Indonesia", "China"], correct:0},
  {text:"Capital de Noruega", options:["Estocolmo", "Copenhague", "Helsinki", "Oslo"], correct:3},
  {text:"¿Qué país tiene forma de bota?", options:["Grecia", "Italia", "España", "Portugal"], correct:1},
  {text:"¿Dónde se encuentra la Isla de Pascua?", options:["Perú", "Chile", "Ecuador", "Colombia"], correct:1},
  {text:"Capital de Irlanda", options:["Belfast", "Cork", "Galway", "Dublín"], correct:3},
  {text:"¿Qué mar separa Europa de África?", options:["Mar Rojo", "Mar Negro", "Mar Mediterráneo", "Mar Caspio"], correct:2},
  {text:"Capital de la India", options:["Bombay", "Calcuta", "Nueva Delhi", "Bangalore"], correct:2},
  {text:"¿Qué cataratas se encuentran en la frontera entre Zambia y Zimbabue?", options:["Cataratas del Niágara", "Cataratas del Iguazú", "Cataratas Victoria", "Salto Ángel"], correct:2},
  {text:"Capital de Suecia", options:["Oslo", "Estocolmo", "Helsinki", "Copenhague"], correct:1},
  {text:"¿En qué país se encuentra la región de la Patagonia?", options:["Brasil y Uruguay", "Chile y Argentina", "Perú y Bolivia", "Colombia y Venezuela"], correct:1},
  {text:"Capital de Grecia", options:["Esparta", "Salónica", "Atenas", "Patras"], correct:2},
  {text:"¿Cuál es la isla más grande del mundo?", options:["Groenlandia", "Nueva Guinea", "Borneo", "Madagascar"], correct:0},
  {text:"Capital de Colombia", options:["Medellín", "Cali", "Cartagena", "Bogotá"], correct:3},
  {text:"¿Qué río es sagrado en la India?", options:["Indo", "Ganges", "Brahmaputra", "Yamuna"], correct:1},
  
  // Historia
  {text:"¿En qué año cayó el Muro de Berlín?", options:["1985", "1989", "1991", "1993"], correct:1},
  {text:"¿Quién fue el primer emperador de Roma?", options:["Julio César", "Augusto", "Nerón", "Calígula"], correct:1},
  {text:"¿En qué año comenzó la Revolución Francesa?", options:["1776", "1789", "1804", "1815"], correct:1},
  {text:"¿Qué civilización construyó las pirámides de Chichén Itzá?", options:["Aztecas", "Incas", "Mayas", "Olmecas"], correct:2},
  {text:"¿En qué guerra participó Juana de Arco?", options:["Guerra de las Rosas", "Guerra de los Cien Años", "Cruzadas", "Guerra de los Treinta Años"], correct:1},
  {text:"¿Quién fue el primer hombre en llegar al espacio?", options:["Neil Armstrong", "Buzz Aldrin", "Yuri Gagarin", "John Glenn"], correct:2},
  {text:"¿En qué año se hundió el Titanic?", options:["1905", "1912", "1918", "1921"], correct:1},
  {text:"¿Qué imperio fue gobernado por Gengis Kan?", options:["Imperio Otomano", "Imperio Romano", "Imperio Persa", "Imperio Mongol"], correct:3},
  {text:"¿Cuál fue la última dinastía de China?", options:["Ming", "Tang", "Song", "Qing"], correct:3},
  {text:"¿Quién fue el primer presidente de Estados Unidos?", options:["Thomas Jefferson", "John Adams", "George Washington", "Benjamin Franklin"], correct:2},
  {text:"¿En qué país comenzó el Renacimiento?", options:["Francia", "España", "Inglaterra", "Italia"], correct:3},
  {text:"¿Qué evento marcó el inicio de la Edad Media?", options:["La caída del Imperio Romano de Occidente", "El descubrimiento de América", "La invención de la imprenta", "La Reforma Protestante"], correct:0},
  {text:"¿Quién lideró la Revolución Rusa de 1917?", options:["Stalin", "Trotsky", "Lenin", "Zar Nicolás II"], correct:2},
  {text:"¿Qué tratado puso fin a la Primera Guerra Mundial?", options:["Tratado de París", "Tratado de Versalles", "Pacto de Acero", "Tratado de Tordesillas"], correct:1},
  {text:"¿Quién fue el faraón de la Gran Pirámide de Giza?", options:["Tutankamón", "Ramsés II", "Keops", "Akenatón"], correct:2},
  {text:"¿En qué siglo vivieron los vikingos su mayor apogeo?", options:["Siglo V al VII", "Siglo VIII al XI", "Siglo XII al XIV", "Siglo XV al XVI"], correct:1},
  {text:"¿Qué reina gobernó Inglaterra durante la época de Shakespeare?", options:["Victoria", "Isabel I", "María I", "Ana"], correct:1},
  {text:"¿Quién lideró la lucha por la independencia de la India?", options:["Jawaharlal Nehru", "Sardar Patel", "Subhas Chandra Bose", "Mahatma Gandhi"], correct:3},
  {text:"¿En qué año llegó el hombre a la Luna?", options:["1965", "1969", "1971", "1975"], correct:1},
  {text:"¿Qué batalla naval de 1805 consolidó el dominio británico en los mares?", options:["Batalla de Lepanto", "Batalla de Trafalgar", "Batalla de Jutlandia", "Batalla de Actium"], correct:1},
  {text:"¿Quién fue el 'Rey Sol' de Francia?", options:["Luis XIII", "Luis XIV", "Luis XV", "Luis XVI"], correct:1},
  {text:"¿Qué país regaló la Estatua de la Libertad a Estados Unidos?", options:["Reino Unido", "España", "Francia", "Alemania"], correct:2},
  {text:"¿Qué guerra se libró entre el Norte y el Sur de Estados Unidos?", options:["Guerra de Independencia", "Guerra de 1812", "Guerra Civil", "Guerra México-Estados Unidos"], correct:2},
  {text:"¿Quién fue el líder de la Reforma Protestante?", options:["Juan Calvino", "Enrique VIII", "Martín Lutero", "Ulrico Zuinglio"], correct:2},
  {text:"¿Cuál fue la 'Ruta de la Seda'?", options:["Una ruta marítima a la India", "Una red de rutas comerciales que conectaba Asia con Europa", "Un camino de peregrinación en España", "Una expedición militar"], correct:1},
  {text:"¿En qué año terminó el Apartheid en Sudáfrica?", options:["1984", "1990", "1994", "2000"], correct:2},
  {text:"¿Qué explorador portugués fue el primero en circunnavegar la Tierra?", options:["Vasco da Gama", "Fernando de Magallanes", "Bartolomé Díaz", "Pedro Álvares Cabral"], correct:1},
  {text:"¿Quién fue el último zar de Rusia?", options:["Iván el Terrible", "Pedro el Grande", "Alejandro II", "Nicolás II"], correct:3},
  {text:"¿En qué ciudad fue asesinado el archiduque Francisco Fernando, desatando la Primera Guerra Mundial?", options:["Viena", "Berlín", "Belgrado", "Sarajevo"], correct:3},
  {text:"¿Qué civilización antigua floreció en la isla de Creta?", options:["Micénica", "Minoica", "Cíclada", "Helenística"], correct:1},

  // Arte y Literatura
  {text:"¿Quién pintó la 'Mona Lisa'?", options:["Miguel Ángel", "Rafael", "Leonardo da Vinci", "Donatello"], correct:2},
  {text:"¿Quién escribió '1984'?", options:["Aldous Huxley", "George Orwell", "Ray Bradbury", "Philip K. Dick"], correct:1},
  {text:"¿Quién es el autor de 'El Principito'?", options:["Albert Camus", "Jean-Paul Sartre", "Antoine de Saint-Exupéry", "Victor Hugo"], correct:2},
  {text:"¿Quién pintó 'La noche estrellada'?", options:["Claude Monet", "Édouard Manet", "Paul Cézanne", "Vincent van Gogh"], correct:3},
  {text:"¿Quién esculpió la estatua de 'David'?", options:["Donatello", "Bernini", "Leonardo da Vinci", "Miguel Ángel"], correct:3},
  {text:"¿Quién escribió 'Orgullo y Prejuicio'?", options:["Charlotte Brontë", "Mary Shelley", "Jane Austen", "Virginia Woolf"], correct:2},
  {text:"¿Quién pintó el 'Guernica'?", options:["Salvador Dalí", "Joan Miró", "Pablo Picasso", "Francisco de Goya"], correct:2},
  {text:"¿Quién escribió 'Matar a un ruiseñor'?", options:["Harper Lee", "Truman Capote", "John Steinbeck", "William Faulkner"], correct:0},
  {text:"¿Cuál de estas obras fue escrita por Fiódor Dostoyevski?", options:["Guerra y Paz", "Anna Karenina", "Crimen y Castigo", "Padres e Hijos"], correct:2},
  {text:"¿Quién es el arquitecto de la Sagrada Familia en Barcelona?", options:["Frank Lloyd Wright", "Le Corbusier", "Antoni Gaudí", "Santiago Calatrava"], correct:2},
  {text:"¿Quién escribió la saga de 'Harry Potter'?", options:["J.R.R. Tolkien", "C.S. Lewis", "Suzanne Collins", "J.K. Rowling"], correct:3},
  {text:"¿Qué movimiento artístico está asociado con Salvador Dalí?", options:["Cubismo", "Impresionismo", "Surrealismo", "Expresionismo"], correct:2},
  {text:"¿Quién escribió 'El viejo y el mar'?", options:["F. Scott Fitzgerald", "Ernest Hemingway", "William Faulkner", "John Steinbeck"], correct:1},
  {text:"¿Quién pintó 'La persistencia de la memoria' (los relojes derretidos)?", options:["René Magritte", "Max Ernst", "Salvador Dalí", "Joan Miró"], correct:2},
  {text:"¿Quién es el autor de 'El extranjero'?", options:["Jean-Paul Sartre", "Albert Camus", "Simone de Beauvoir", "André Gide"], correct:1},
  {text:"¿Qué artista es famoso por sus 'ready-mades'?", options:["Andy Warhol", "Marcel Duchamp", "Jackson Pollock", "Piet Mondrian"], correct:1},
  {text:"¿Quién escribió 'Moby Dick'?", options:["Nathaniel Hawthorne", "Herman Melville", "Mark Twain", "Edgar Allan Poe"], correct:1},
  {text:"¿Quién pintó 'El nacimiento de Venus'?", options:["Tiziano", "Caravaggio", "Sandro Botticelli", "Giotto"], correct:2},
  {text:"¿Quién escribió la 'Divina Comedia'?", options:["Petrarca", "Boccaccio", "Maquiavelo", "Dante Alighieri"], correct:3},
  {text:"¿Qué artista es una figura clave del Pop Art?", options:["Roy Lichtenstein", "Andy Warhol", "Keith Haring", "Todos los anteriores"], correct:3},
  {text:"¿Quién escribió 'Frankenstein'?", options:["Jane Austen", "Mary Shelley", "Bram Stoker", "Emily Brontë"], correct:1},
  {text:"¿Quién compuso 'Las cuatro estaciones'?", options:["Bach", "Mozart", "Beethoven", "Vivaldi"], correct:3},
  {text:"¿Quién escribió 'Ulises'?", options:["Virginia Woolf", "T.S. Eliot", "James Joyce", "Ezra Pound"], correct:2},
  {text:"¿Quién pintó 'Las meninas'?", options:["El Greco", "Goya", "Velázquez", "Murillo"], correct:2},
  {text:"¿Quién es el autor de la saga 'El Señor de los Anillos'?", options:["George R.R. Martin", "C.S. Lewis", "J.R.R. Tolkien", "Terry Pratchett"], correct:2},
  {text:"¿Quién compuso la 'Novena Sinfonía'?", options:["Mozart", "Haydn", "Beethoven", "Schubert"], correct:2},
  {text:"¿Quién escribió 'El Gran Gatsby'?", options:["Ernest Hemingway", "F. Scott Fitzgerald", "John Steinbeck", "Tennessee Williams"], correct:1},
  {text:"¿Qué pintor holandés es famoso por sus autorretratos y la obra 'La ronda de noche'?", options:["Vermeer", "Rembrandt", "Hals", "Van Gogh"], correct:1},
  {text:"¿Quién es la autora de la serie de novelas 'Los juegos del hambre'?", options:["Veronica Roth", "Suzanne Collins", "J.K. Rowling", "Stephenie Meyer"], correct:1},
  {text:"¿Quién compuso la ópera 'La flauta mágica'?", options:["Beethoven", "Verdi", "Mozart", "Puccini"], correct:2},
  
  // Ciencia y Descubrimientos
  {text:"¿Cuál es el símbolo químico del oro?", options:["Ag", "Au", "Fe", "Pb"], correct:1},
  {text:"¿Qué científico propuso la teoría de la relatividad?", options:["Isaac Newton", "Galileo Galilei", "Nikola Tesla", "Albert Einstein"], correct:3},
  {text:"¿Quién descubrió la penicilina?", options:["Marie Curie", "Louis Pasteur", "Alexander Fleming", "Robert Koch"], correct:2},
  {text:"¿Qué es H₂O?", options:["Dióxido de Carbono", "Oxígeno", "Agua", "Hidrógeno"], correct:2},
  {text:"¿Qué planeta está más cerca del Sol?", options:["Venus", "Tierra", "Mercurio", "Marte"], correct:2},
  {text:"¿Cuál es la unidad básica de la vida?", options:["El átomo", "La molécula", "La célula", "El tejido"], correct:2},
  {text:"¿Quién es considerado el padre de la genética?", options:["Charles Darwin", "Gregor Mendel", "Louis Pasteur", "Alfred Wallace"], correct:1},
  {text:"¿Qué gas es esencial para la respiración humana?", options:["Nitrógeno", "Dióxido de Carbono", "Oxígeno", "Argón"], correct:2},
  {text:"¿Cuál es el metal más ligero?", options:["Aluminio", "Magnesio", "Litio", "Titanio"], correct:2},
  {text:"¿Qué ley de la física describe la gravedad?", options:["Leyes de Kepler", "Ley de Ohm", "Leyes de Newton", "Ley de la Gravitación Universal"], correct:3},
  {text:"¿Cuál es el símbolo químico de la plata?", options:["Si", "Ag", "Al", "Au"], correct:1},
  {text:"¿Quién desarrolló la primera vacuna?", options:["Louis Pasteur", "Robert Koch", "Edward Jenner", "Jonas Salk"], correct:2},
  {text:"¿Qué mide la escala de Richter?", options:["La velocidad del viento", "La temperatura", "La intensidad de los terremotos", "La presión atmosférica"], correct:2},
  {text:"¿Cuál es el elemento más abundante en el universo?", options:["Oxígeno", "Helio", "Carbono", "Hidrógeno"], correct:3},
  {text:"¿Quién propuso el modelo heliocéntrico del sistema solar?", options:["Ptolomeo", "Aristóteles", "Copérnico", "Galileo"], correct:2},
  {text:"¿Qué es el ADN?", options:["Ácido desoxirribonucleico", "Ácido ribonucleico", "Adenosín trifosfato", "Aminoácido"], correct:0},
  {text:"¿Cuál es el hueso más largo del cuerpo humano?", options:["Tibia", "Peroné", "Húmero", "Fémur"], correct:3},
  {text:"¿Qué vitamina se obtiene principalmente de la exposición al sol?", options:["Vitamina A", "Vitamina C", "Vitamina D", "Vitamina B12"], correct:2},
  {text:"¿Quién inventó el teléfono?", options:["Thomas Edison", "Nikola Tesla", "Alexander Graham Bell", "Guglielmo Marconi"], correct:2},
  {text:"¿Cuál es la velocidad de la luz?", options:["300,000 km/h", "300,000 km/s", "150,000 km/s", "1,000,000 km/s"], correct:1},
  {text:"¿Qué parte de la planta realiza la fotosíntesis?", options:["La raíz", "El tallo", "La flor", "La hoja"], correct:3},
  {text:"¿Cuál es el símbolo químico del hierro?", options:["Hi", "He", "Fe", "Ir"], correct:2},
  {text:"¿Quién es famosa por su investigación sobre la radiactividad?", options:["Rosalind Franklin", "Ada Lovelace", "Marie Curie", "Lise Meitner"], correct:2},
  {text:"¿Cuántos planetas hay en nuestro sistema solar?", options:["7", "8", "9", "10"], correct:1},
  {text:"¿Qué es la 'materia oscura'?", options:["Un tipo de agujero negro", "Materia que no emite luz", "El espacio entre galaxias", "Una forma de antimateria"], correct:1},
  {text:"¿Cuál es el gas más abundante en la atmósfera terrestre?", options:["Oxígeno", "Nitrógeno", "Dióxido de Carbono", "Argón"], correct:1},
  {text:"¿Quién inventó la bombilla incandescente?", options:["Nikola Tesla", "Thomas Edison", "Benjamin Franklin", "Alessandro Volta"], correct:1},
  {text:"¿Qué estudia la entomología?", options:["Peces", "Aves", "Reptiles", "Insectos"], correct:3},
  {text:"¿Cuál es la fórmula química de la sal de mesa?", options:["KCl", "CaCl₂", "NaCl", "MgCl₂"], correct:2},
  {text:"¿Quién desarrolló la tabla periódica de los elementos?", options:["Dmitri Mendeléyev", "Antoine Lavoisier", "John Dalton", "J.J. Thomson"], correct:0},

  // Cultura Popular, Deportes y Tradiciones
  {text:"¿Qué banda es conocida como 'Los cuatro de Liverpool'?", options:["The Rolling Stones", "The Who", "The Kinks", "The Beatles"], correct:3},
  {text:"¿Quién dirigió la trilogía de 'El Padrino'?", options:["Martin Scorsese", "Steven Spielberg", "Francis Ford Coppola", "Quentin Tarantino"], correct:2},
  {text:"¿Qué país ganó la primera Copa Mundial de la FIFA en 1930?", options:["Argentina", "Brasil", "Italia", "Uruguay"], correct:3},
  {text:"¿En qué ciudad se celebraron los primeros Juegos Olímpicos modernos en 1896?", options:["París", "Londres", "Atenas", "Roma"], correct:2},
  {text:"¿Cómo se llama el martillo de Thor?", options:["Gungnir", "Mjolnir", "Stormbreaker", "Excalibur"], correct:1},
  {text:"¿Qué plato es típico de la gastronomía de España?", options:["Sushi", "Pizza", "Paella", "Tacos"], correct:2},
  {text:"¿Qué festival se celebra en la India y es conocido como el 'festival de las luces'?", options:["Holi", "Diwali", "Navaratri", "Dussehra"], correct:1},
  {text:"¿De qué país es originaria la danza del tango?", options:["Brasil", "España", "Colombia", "Argentina"], correct:3},
  {text:"¿Quién es el creador de los personajes de 'Star Wars'?", options:["Steven Spielberg", "James Cameron", "J.J. Abrams", "George Lucas"], correct:3},
  {text:"¿Cuál es el deporte nacional de Canadá?", options:["Hockey sobre hielo y Lacrosse", "Béisbol", "Fútbol", "Baloncesto"], correct:0},
  {text:"¿Qué actor interpretó a James Bond en la película 'Casino Royale' (2006)?", options:["Pierce Brosnan", "Sean Connery", "Daniel Craig", "Roger Moore"], correct:2},
  {text:"¿Cómo se llama la moneda oficial de Japón?", options:["Yuan", "Won", "Yen", "Baht"], correct:2},
  {text:"¿Qué es el 'Oktoberfest'?", options:["Un festival de cine en Berlín", "Un festival de la cerveza en Múnich", "Un carnaval en Colonia", "Un mercado navideño en Núremberg"], correct:1},
  {text:"¿Cuál es el seudónimo del superhéroe Bruce Wayne?", options:["Superman", "Spider-Man", "Batman", "Iron Man"], correct:2},
  {text:"¿En qué deporte se destaca Michael Jordan?", options:["Béisbol", "Fútbol Americano", "Baloncesto", "Golf"], correct:2},
  {text:"¿Qué es un kimono?", options:["Una comida japonesa", "Un arte marcial", "Una vestimenta tradicional japonesa", "Un tipo de espada"], correct:2},
  {text:"¿Quién cantó la canción 'Bohemian Rhapsody'?", options:["Led Zeppelin", "Queen", "Pink Floyd", "The Rolling Stones"], correct:1},
  {text:"¿Qué película ganó el primer Óscar a la Mejor Película?", options:["Lo que el viento se llevó", "Casablanca", "Alas", "Sucedió una noche"], correct:2},
  {text:"¿Qué es el 'Día de los Muertos'?", options:["Una fiesta de Halloween en México", "Una celebración mexicana para honrar a los difuntos", "El año nuevo mexicano", "El día de la independencia de México"], correct:1},
  {text:"¿Cuál es el nombre del hechicero director de Hogwarts?", options:["Severus Snape", "Albus Dumbledore", "Sirius Black", "Lord Voldemort"], correct:1},
  {text:"¿Qué instrumento es famoso por ser tocado por los gaiteros escoceses?", options:["Clarinete", "Gaita", "Acordeón", "Trompeta"], correct:1},
  {text:"¿Qué es el 'sushi'?", options:["Una sopa japonesa", "Un plato japonés de arroz avinagrado con otros ingredientes", "Un tipo de té verde", "Un postre de frijoles rojos"], correct:1},
  {text:"¿En qué país se originó el juego de ajedrez?", options:["China", "Egipto", "Grecia", "India"], correct:3},
  {text:"¿Quién es el máximo goleador en la historia de la Copa del Mundo de la FIFA?", options:["Pelé", "Ronaldo Nazário", "Lionel Messi", "Miroslav Klose"], correct:3},
  {text:"¿Qué significa 'Hakuna Matata'?", options:["'Hola, amigo'", "'No te preocupes'", "'Hasta luego'", "'Te quiero'"], correct:1},
  {text:"¿De qué país es originario el 'reggae'?", options:["Cuba", "Jamaica", "Haití", "Barbados"], correct:1},
  {text:"¿Qué es el 'Carnaval de Río'?", options:["Un festival religioso", "Un desfile militar", "Un famoso festival de desfiles de samba en Brasil", "Una carrera de autos"], correct:2},
  {text:"¿Quién dirigió la película 'Titanic'?", options:["George Lucas", "Steven Spielberg", "James Cameron", "Christopher Nolan"], correct:2},
  {text:"¿Qué selección de fútbol es conocida como 'La Naranja Mecánica'?", options:["Alemania", "Bélgica", "Países Bajos", "Dinamarca"], correct:2},
  {text:"¿Qué es el 'origami'?", options:["El arte japonés de la caligrafía", "El arte japonés del arreglo floral", "El arte japonés del plegado de papel", "La ceremonia japonesa del té"], correct:2},
  
  // Rondas adicionales de temas variados
  {text:"¿Qué es la Acrópolis de Atenas?", options:["Un mercado antiguo", "Un templo dedicado a Zeus", "Una ciudadela en una colina con varios templos antiguos", "Un teatro romano"], correct:2},
  {text:"¿Quién fue Cleopatra?", options:["Una diosa romana", "Una reina de Esparta", "La última reina del Antiguo Egipto", "Una emperatriz china"], correct:2},
  {text:"¿Cuál es el libro sagrado del Islam?", options:["La Torá", "La Biblia", "El Corán", "Los Vedas"], correct:2},
  {text:"¿En qué ciudad se encuentra el Coliseo Romano?", options:["Atenas", "Roma", "Milán", "Florencia"], correct:1},
  {text:"¿Qué instrumento tocaba Jimi Hendrix de manera icónica?", options:["Batería", "Bajo", "Teclado", "Guitarra eléctrica"], correct:3},
  {text:"¿Cuál de estos no es uno de los cinco pilares del Islam?", options:["La oración (Salat)", "El ayuno (Sawm)", "La peregrinación (Hajj)", "La meditación (Dhyana)"], correct:3},
  {text:"¿Quién fue el líder del movimiento por los derechos civiles en Estados Unidos en la década de 1960?", options:["Malcolm X", "Martin Luther King Jr.", "Rosa Parks", "Jesse Jackson"], correct:1},
  {text:"¿Cuál es la moneda del Reino Unido?", options:["Euro", "Dólar", "Franco", "Libra esterlina"], correct:3},
  {text:"¿En qué país se originó la pizza moderna?", options:["Grecia", "Francia", "Italia", "Estados Unidos"], correct:2},
  {text:"¿Cuál es el animal nacional de Australia?", options:["Koala", "Wombat", "Canguro", "Emú"], correct:2},
  {text:"¿Qué es el 'sake'?", options:["Una salsa de soja", "Una sopa de miso", "Un licor de arroz japonés", "Un tipo de fideo"], correct:2},
  {text:"¿Quién escribió 'El diario de Ana Frank'?", options:["Ana Frank", "Otto Frank", "Miep Gies", "Corrie ten Boom"], correct:0},
  {text:"¿Cuál de estas ciudades no es una capital?", options:["Sídney", "Ottawa", "Wellington", "Berna"], correct:0},
  {text:"¿Qué significan las siglas 'NASA'?", options:["Agencia Nacional del Aire y el Espacio", "Asociación Norteamericana de Seguridad Aérea", "Administración Nacional de Aeronáutica y el Espacio", "Organización de Navegación y Astro-exploración"], correct:2},
  {text:"¿Cuál es el principal ingrediente del guacamole?", options:["Tomate", "Cebolla", "Aguacate", "Chile"], correct:2},
  {text:"¿Qué es el 'feng shui'?", options:["Un tipo de arte marcial", "Un sistema filosófico chino de armonización del entorno", "Una forma de meditación", "Una ceremonia del té"], correct:1},
  {text:"¿Quién fue el primer ser humano en caminar sobre la Luna?", options:["Yuri Gagarin", "Buzz Aldrin", "Michael Collins", "Neil Armstrong"], correct:3},
  {text:"¿Qué es un 'haiku'?", options:["Un tipo de pintura japonesa", "Una forma corta de poesía japonesa", "Una espada de samurái", "Un jardín zen"], correct:1},
  {text:"¿En qué deporte compite Roger Federer?", options:["Golf", "Fútbol", "Tenis", "Fórmula 1"], correct:2},
  {text:"¿Cuál es el libro sagrado del judaísmo?", options:["El Corán", "El Nuevo Testamento", "La Torá", "El Libro de Mormón"], correct:2},
  {text:"¿En qué ciudad se encuentra el museo del Louvre?", options:["Londres", "Madrid", "Roma", "París"], correct:3},
  {text:"¿Qué civilización es famosa por sus cabezas colosales de piedra?", options:["Maya", "Zapoteca", "Olmeca", "Tolteca"], correct:2},
  {text:"¿Qué es el 'braille'?", options:["Un lenguaje de señas", "Un sistema de escritura táctil para ciegos", "Un código de comunicación por radio", "Un tipo de taquigrafía"], correct:1},
  {text:"¿Cuál es la capital de Finlandia?", options:["Estocolmo", "Oslo", "Copenhague", "Helsinki"], correct:3},
  {text:"¿Qué es la 'salsa' en términos musicales?", options:["Un condimento picante", "Un género musical bailable de origen cubano", "Un tipo de tela", "Un paso de baile flamenco"], correct:1},
  {text:"¿Quién pintó la Capilla Sixtina?", options:["Leonardo da Vinci", "Rafael", "Miguel Ángel", "Tiziano"], correct:2},
  {text:"¿Cuál es el animal que aparece en el logo de Porsche?", options:["Toro", "León", "Caballo", "Jaguar"], correct:2},
  {text:"¿Qué es la 'sari'?", options:["Una especia india", "Una danza tradicional", "Una prenda de vestir femenina del subcontinente indio", "Un festival religioso"], correct:2},
  {text:"¿Qué banda de rock interpretó la famosa canción 'Stairway to Heaven'?", options:["The Doors", "Led Zeppelin", "Deep Purple", "Black Sabbath"], correct:1},
  {text:"¿Cuál es el principal gas de efecto invernadero?", options:["Metano", "Óxido nitroso", "Dióxido de carbono", "Ozono"], correct:2},
  {text:"¿Qué es un 'fjord' (fiordo)?", options:["Un tipo de montaña", "Un desierto de hielo", "Un valle profundo y estrecho inundado por el mar", "Un lago volcánico"], correct:2},
  {text:"¿En qué país se encuentra la Torre de Pisa?", options:["Francia", "España", "Grecia", "Italia"], correct:3},
  {text:"¿Quién es el creador de 'Los Simpson'?", options:["Seth MacFarlane", "Mike Judge", "Matt Groening", "Trey Parker"], correct:2},
  {text:"¿Cuál es el estadio de fútbol más grande del mundo (por capacidad)?", options:["Camp Nou", "Wembley", "Estadio Rungrado 1º de Mayo", "Melbourne Cricket Ground"], correct:2},
  {text:"¿Qué es el 'k-pop'?", options:["Un plato tradicional coreano", "Un género de música popular de Corea del Sur", "Un drama televisivo coreano", "Un estilo de moda coreano"], correct:1},
  {text:"¿Qué es la 'Piedra de Rosetta'?", options:["Una joya de la corona egipcia", "Una roca lunar", "Una estela que permitió descifrar los jeroglíficos egipcios", "La primera herramienta de piedra descubierta"], correct:2},
  {text:"¿Qué país es el mayor productor de café del mundo?", options:["Colombia", "Vietnam", "Brasil", "Etiopía"], correct:2},
  {text:"¿Cuál es el nombre del barco de Han Solo?", options:["Starship Enterprise", "Halcón Milenario", "Serenity", "Nostromo"], correct:1},
  {text:"¿Qué es el 'sumo'?", options:["Una sopa japonesa", "Un estilo de lucha japonés", "Un tipo de tambor", "Una ceremonia religiosa"], correct:1},
  {text:"¿En qué ciudad europea puedes encontrar el 'Manneken Pis'?", options:["Ámsterdam", "Luxemburgo", "Bruselas", "Ginebra"], correct:2},
  {text:"¿Cuál es la capital de Nueva Zelanda?", options:["Auckland", "Christchurch", "Wellington", "Queenstown"], correct:2},
  {text:"¿Qué explorador es acreditado con el 'descubrimiento' de Australia para los británicos?", options:["Abel Tasman", "James Cook", "Francis Drake", "Vasco da Gama"], correct:1},
  {text:"¿Qué dios griego era el mensajero de los dioses?", options:["Apolo", "Hefesto", "Hermes", "Dionisio"], correct:2},
  {text:"¿Qué país celebra el 'Año Nuevo Chino'?", options:["Japón", "Tailandia", "China", "Corea del Sur"], correct:2},
  {text:"¿Cuál es el nombre del león en 'El Rey León'?", options:["Mufasa", "Simba", "Scar", "Zazú"], correct:1},
  {text:"¿En qué país se originó el ballet?", options:["Rusia", "Francia", "Italia", "Dinamarca"], correct:2},
  {text:"¿Qué es un 'glaciar'?", options:["Una montaña de hielo", "Un río congelado", "Una gruesa masa de hielo que se origina en la tierra", "Un iceberg en el mar"], correct:2},
  {text:"¿Cuál de estos compositores es del período romántico?", options:["Bach", "Mozart", "Chopin", "Vivaldi"], correct:2},
  {text:"¿Qué es el 'ceviche'?", options:["Un plato de carne asada", "Un plato de pescado o marisco marinado en cítricos", "Una sopa de frijoles", "Un postre de leche"], correct:1},
  {text:"¿En qué país se encuentra Stonehenge?", options:["Irlanda", "Escocia", "Gales", "Inglaterra"], correct:3},
  {text:"¿Cuál es el nombre del mago en 'El Señor de los Anillos'?", options:["Dumbledore", "Merlín", "Saruman", "Gandalf"], correct:3},
  {text:"¿Qué es la 'seda'?", options:["Una fibra vegetal", "Una fibra sintética", "Una fibra natural producida por un insecto", "Un tipo de lana"], correct:2},
  {text:"¿En qué ciudad se encuentra el 'Puente de la Torre' (Tower Bridge)?", options:["París", "Praga", "Budapest", "Londres"], correct:3},
  {text:"¿Quién fue el primer presidente de Sudáfrica elegido democráticamente?", options:["F. W. de Klerk", "Thabo Mbeki", "Nelson Mandela", "Jacob Zuma"], correct:2},
  {text:"¿Qué es la 'capoeira'?", options:["Un plato brasileño", "Una forma de arte marcial afro-brasileña que combina danza y música", "Un instrumento musical", "Un festival religioso"], correct:1},
  {text:"¿Qué cadena montañosa separa Europa de Asia?", options:["Los Alpes", "Los Urales", "El Cáucaso", "Los Cárpatos"], correct:1},
  {text:"¿Quién dirigió la película 'Pulp Fiction'?", options:["Martin Scorsese", "Quentin Tarantino", "David Fincher", "Spike Lee"], correct:1},
  {text:"¿Cuál es el océano más pequeño del mundo?", options:["Índico", "Antártico", "Atlántico", "Ártico"], correct:3},
  {text:"¿Qué es el 'hummus'?", options:["Una pasta de berenjena", "Una ensalada de pepino", "Una crema de garbanzos", "Un pan plano"], correct:2},
  {text:"¿Cuál es el elemento químico más pesado que se encuentra de forma natural?", options:["Oro", "Plomo", "Uranio", "Plutonio"], correct:2},
  {text:"¿Qué es un 'tsunami'?", options:["Un huracán", "Un tornado sobre el agua", "Una serie de olas oceánicas gigantes causadas por perturbaciones submarinas", "Una tormenta tropical"], correct:2},
  {text:"¿En qué país se encuentra la Ópera de Sídney?", options:["Nueva Zelanda", "Australia", "Sudáfrica", "Canadá"], correct:1},
  {text:"¿Quién compuso la melodía de 'Para Elisa'?", options:["Mozart", "Bach", "Chopin", "Beethoven"], correct:3},
  {text:"¿Qué es el 'mate'?", options:["Un tipo de té", "Una infusión hecha con hojas de yerba mate", "Un café fuerte", "Un licor de hierbas"], correct:1},
  {text:"¿Cuál es el nombre del dios principal en la mitología nórdica?", options:["Thor", "Loki", "Odín", "Frey"], correct:2},
  {text:"¿De qué país es la marca de automóviles Volvo?", options:["Alemania", "Suecia", "Japón", "Italia"], correct:1},
  {text:"¿Qué es la 'Gran Barrera de Coral'?", options:["La muralla más larga del mundo", "El arrecife de coral más grande del mundo", "Una cadena montañosa submarina", "Un grupo de islas volcánicas"], correct:1},
  {text:"¿En qué ciudad se encuentra el Kremlin?", options:["San Petersburgo", "Kiev", "Moscú", "Varsovia"], correct:2},
  {text:"¿Qué es el 'papiro'?", options:["Un tipo de tela", "Un material de escritura hecho de una planta acuática", "Una especia antigua", "Un pigmento para pintar"], correct:1},
  {text:"¿Quién escribió 'Las aventuras de Tom Sawyer'?", options:["Herman Melville", "Nathaniel Hawthorne", "Mark Twain", "Jack London"], correct:2},
  {text:"¿Qué pigmento le da el color verde a las plantas?", options:["Nitrógeno", "Oxígeno", "Clorofila", "Dióxido de carbono"], correct:2},
  {text:"¿Qué país tiene el mayor número de volcanes activos?", options:["Japón", "Filipinas", "Indonesia", "Estados Unidos"], correct:2},
  {text:"¿Quién es el rey del rock and roll?", options:["Chuck Berry", "Elvis Presley", "Little Richard", "Jerry Lee Lewis"], correct:1},
  {text:"¿Qué es un 'menhir'?", options:["Una tumba prehistórica", "Un monumento megalítico que consiste en una piedra vertical", "Un círculo de piedras", "Una cueva con pinturas"], correct:1},
  {text:"¿Cuál es la capital de Escocia?", options:["Glasgow", "Aberdeen", "Dundee", "Edimburgo"], correct:3},
  {text:"¿Qué es el 'goulash'?", options:["Un postre austríaco", "Una sopa o estofado de carne y verduras, sazonado con pimentón, de origen húngaro", "Una salchicha alemana", "Un queso suizo"], correct:1},
  {text:"¿En qué deporte es famoso Usain Bolt?", options:["Natación", "Atletismo", "Gimnasia", "Ciclismo"], correct:1},
  {text:"¿Cuál es la religión principal de Tailandia?", options:["Islam", "Cristianismo", "Hinduismo", "Budismo"], correct:3},
  {text:"¿Qué es el 'bumerán'?", options:["Un arma arrojadiza asociada con los aborígenes australianos", "Un instrumento musical", "Un tipo de canoa", "Una herramienta de caza"], correct:0},
  {text:"¿Quién fue Leonardo da Vinci?", options:["Solo un pintor", "Solo un escultor", "Solo un inventor", "Un polímata: pintor, inventor, científico y más"], correct:3},
  {text:"¿Qué es la 'aurora boreal'?", options:["Un fenómeno meteorológico", "Un eclipse solar", "Un fenómeno luminoso en el cielo nocturno, usualmente en zonas polares", "Un tipo de nube"], correct:2},
  {text:"¿En qué país se encuentra el 'Salto Ángel', la cascada más alta del mundo?", options:["Brasil", "Colombia", "Perú", "Venezuela"], correct:3},
  {text:"¿Quién escribió 'La Metamorfosis'?", options:["Hermann Hesse", "Thomas Mann", "Franz Kafka", "Rainer Maria Rilke"], correct:2},
  {text:"¿Qué es el 'curry'?", options:["Un solo tipo de especia", "Un plato del sur de la India", "Un nombre general para una variedad de platos especiados del sudeste asiático", "Un tipo de pan plano"], correct:2},
  {text:"¿Cuál es el nombre de la galaxia en la que se encuentra nuestro sistema solar?", options:["Andrómeda", "Triángulo", "Sombrero", "Vía Láctea"], correct:3},
  {text:"¿Qué es un 'samurái'?", options:["Un emperador japonés", "Un tipo de monje", "Un guerrero del antiguo Japón", "Un comerciante"], correct:2},
  {text:"¿Cuál es la capital de Vietnam?", options:["Ciudad Ho Chi Minh", "Da Nang", "Hanoi", "Hué"], correct:2},
  {text:"¿Qué civilización inventó la escritura cuneiforme?", options:["Egipcia", "Griega", "Romana", "Sumeria"], correct:3},
  {text:"¿Quién es considerado el 'padre de la computadora'?", options:["Alan Turing", "Charles Babbage", "John von Neumann", "Bill Gates"], correct:1},
  {text:"¿Qué son los 'moáis'?", options:["Templos mayas", "Estatuas monolíticas en la Isla de Pascua", "Pirámides aztecas", "Geoglifos en Perú"], correct:1},
  {text:"¿Qué instrumento es el protagonista en un cuarteto de cuerdas?", options:["Piano", "Contrabajo", "Violín", "Clarinete"], correct:2},
  {text:"¿Cuál es el animal nacional de la India?", options:["Elefante", "León", "Tigre de Bengala", "Pavo real"], correct:2},
  {text:"¿Qué es el 'ikebana'?", options:["El arte japonés de la caligrafía", "El arte japonés del arreglo floral", "La ceremonia del té japonesa", "El teatro de marionetas japonés"], correct:1},
  {text:"¿Qué es el 'Big Ben'?", options:["La torre del reloj", "El reloj en sí", "La campana principal dentro de la torre del reloj", "El palacio de Westminster"], correct:2},
  {text:"¿Cuál es la capital de Marruecos?", options:["Casablanca", "Marrakech", "Fez", "Rabat"], correct:3},
  {text:"¿Qué es la 'salsa de soja'?", options:["Un condimento hecho de chiles", "Un condimento hecho de soja fermentada", "Una pasta de sésamo", "Un vinagre de arroz"], correct:1},
  {text:"¿Qué famoso físico formuló las tres leyes del movimiento?", options:["Albert Einstein", "Galileo Galilei", "Isaac Newton", "Johannes Kepler"], correct:2},
  {text:"¿Cuál es el idioma oficial de Brasil?", options:["Español", "Inglés", "Francés", "Portugués"], correct:3},
  {text:"¿Qué es la 'Cámara Oscura'?", options:["Un cuarto de tortura medieval", "Un instrumento óptico que es precursor de la fotografía", "Una sociedad secreta", "Una cueva sin luz"], correct:1},
  {text:"¿Quién fue 'El Libertador' de varios países de Sudamérica?", options:["José de San Martín", "Bernardo O'Higgins", "Simón Bolívar", "Antonio José de Sucre"], correct:2},
  {text:"¿Qué es un 'iglú'?", options:["Una tienda de campaña de piel", "Una casa de madera", "Una vivienda construida con bloques de nieve", "Una cueva en una montaña"], correct:2},
  {text:"¿Cuál es el ingrediente principal del 'masala chai'?", options:["Café", "Té negro", "Té verde", "Té de hierbas"], correct:1},
  {text:"¿Qué es la 'Acrópolis'?", options:["El mercado principal de una ciudad griega", "El templo de un dios griego", "Una ciudadela fortificada en la parte más alta de una ciudad griega", "Un teatro al aire libre"], correct:2},
  {text:"¿Cuál es el océano que rodea la Antártida?", options:["Pacífico", "Atlántico", "Índico", "Antártico (o Austral)"], correct:3},
  {text:"¿Qué artista del Renacimiento NO es famoso por la escultura de 'El Pensador'?", options:["Miguel Ángel", "Donatello", "Leonardo da Vinci", "Auguste Rodin"], correct:3},
  {text:"¿Qué es el 'panteón' en la mitología?", options:["Un único dios supremo", "Un templo dedicado a todos los dioses", "El conjunto de todos los dioses de una mitología", "Un héroe semidiós"], correct:2},
  {text:"¿Cuál es la capital de Austria?", options:["Múnich", "Praga", "Budapest", "Viena"], correct:3},
  {text:"¿Qué es el 'origami'?", options:["El arte japonés de la caligrafía", "El arte japonés del plegado de papel", "Un tipo de comida japonesa", "Un arte marcial"], correct:1},
  {text:"¿En qué país se originó la Reforma Protestante?", options:["Inglaterra", "Suiza", "Francia", "Alemania"], correct:3},
  {text:"¿Cuál es el nombre del palacio real en Madrid?", options:["Palacio de Versalles", "Palacio de Buckingham", "Palacio Real de Madrid", "Palacio de Schönbrunn"], correct:2},
  {text:"¿Qué es el 'sushi'?", options:["Pescado crudo", "Arroz avinagrado acompañado de otros ingredientes como pescado", "Una sopa de algas", "Fideos japoneses"], correct:1},
  {text:"¿Qué expedición completó la primera circunnavegación del globo?", options:["La de Cristóbal Colón", "La de Vasco da Gama", "La de Magallanes-Elcano", "La de James Cook"], correct:2},
  {text:"¿Cuál es la moneda de Suiza?", options:["Euro", "Corona", "Libra", "Franco suizo"], correct:3},
  {text:"¿Qué es el 'Carnaval'?", options:["Una festividad religiosa solemne", "Una celebración pública que combina desfiles, disfraces y fiestas callejeras", "Un festival de la cosecha", "Un día nacional de independencia"], correct:1},
  {text:"¿Quién pintó 'El Grito'?", options:["Vincent van Gogh", "Paul Gauguin", "Claude Monet", "Edvard Munch"], correct:3},
  {text:"¿Qué es la 'Estupa' en la arquitectura budista?", options:["Un templo", "Un monasterio", "Una estructura en forma de cúpula que contiene reliquias", "Una sala de oración"], correct:2},
  {text:"¿Cuál es la capital de Dinamarca?", options:["Oslo", "Estocolmo", "Copenhague", "Helsinki"], correct:2},
  {text:"¿Qué es un 'menú degustación'?", options:["Un menú con platos más baratos", "Un menú compuesto por pequeñas porciones de varios platos del chef", "Un menú para niños", "Un menú para llevar"], correct:1},
  {text:"¿Cuál es el nombre del dios egipcio del sol?", options:["Osiris", "Anubis", "Horus", "Ra"], correct:3},
  {text:"¿Qué es la 'caligrafía'?", options:["El arte de dibujar mapas", "El arte de escribir bellamente", "El arte de la escultura en piedra", "El arte de la encuadernación de libros"], correct:1},
  {text:"¿En qué país se encuentra la Gran Esfinge de Giza?", options:["Grecia", "Turquía", "Egipto", "Irán"], correct:2},
  {text:"¿Cuál es el deporte más popular del mundo?", options:["Críquet", "Baloncesto", "Fútbol", "Tenis"], correct:2},
  {text:"¿Qué es el 'Yeti'?", options:["Un monstruo marino", "Un dios del Himalaya", "Una criatura mítica similar a un simio que se dice habita en el Himalaya", "Un tipo de monje tibetano"], correct:2},
  {text:"¿Quién escribió la obra de teatro 'Romeo y Julieta'?", options:["Christopher Marlowe", "Ben Jonson", "William Shakespeare", "John Webster"], correct:2},
  {text:"¿Qué es la 'seda'?", options:["Una fibra vegetal", "Una fibra producida por las larvas de una polilla", "Una fibra sintética", "Un tipo de lana"], correct:1},
  {text:"¿Cuál es el idioma más hablado en el mundo por número total de hablantes?", options:["Mandarín", "Español", "Inglés", "Hindi"], correct:2},
  {text:"¿Qué es un 'tótem'?", options:["Un tipo de vivienda", "Un arma de caza", "Un objeto o ser que sirve como emblema de un clan o tribu", "Un instrumento musical"], correct:2},
  {text:"¿En qué ciudad se encuentra el 'Muro de las Lamentaciones'?", options:["Roma", "Estambul", "Jerusalén", "La Meca"], correct:2},
  {text:"¿Qué es el 'gazpacho'?", options:["Una sopa caliente de carne", "Una sopa fría a base de hortalizas crudas, originaria de España", "Un postre de frutas", "Una bebida alcohólica"], correct:1},
  {text:"¿Qué civilización construyó la ciudad de Teotihuacán?", options:["Aztecas", "Mayas", "Toltecas", "Una civilización anterior a los aztecas"], correct:3},
  {text:"¿Qué es la 'samba'?", options:["Un plato brasileño", "Un género musical y forma de baile brasileño", "Un río en Brasil", "Una prenda de vestir"], correct:1},
  {text:"¿Cuál es el animal nacional de China?", options:["Tigre", "Dragón (mítico)", "Grulla de corona roja", "Panda gigante"], correct:3},
  {text:"¿Qué es el 'Coliseo'?", options:["Un palacio romano", "Un templo para todos los dioses", "Un anfiteatro en el centro de Roma", "Un mercado público"], correct:2},
  {text:"¿Qué es un 'gurú' en el hinduismo y el sijismo?", options:["Un dios", "Un sacerdote", "Un maestro espiritual", "Un rey"], correct:2},
  {text:"¿Cuál es la capital de Bélgica?", options:["Ámsterdam", "Luxemburgo", "Bruselas", "Lille"], correct:2},
  {text:"¿Qué es la 'UNESCO'?", options:["Una organización económica mundial", "Una alianza militar", "La Organización de las Naciones Unidas para la Educación, la Ciencia y la Cultura", "Un tribunal internacional"], correct:2},
  {text:"¿Qué es un 'zoco'?", options:["Un palacio en el Medio Oriente", "Un desierto", "El mercado tradicional en una ciudad árabe", "Una fortaleza"], correct:2},
  {text:"¿Qué país es famoso por sus molinos de viento y tulipanes?", options:["Bélgica", "Dinamarca", "Alemania", "Países Bajos"], correct:3},
  {text:"¿Quién es el autor de 'El retrato de Dorian Gray'?", options:["Charles Dickens", "Oscar Wilde", "George Bernard Shaw", "H. G. Wells"], correct:1},
  {text:"¿Qué es el 'yin y el yang'?", options:["Dos dioses chinos", "Un concepto del taoísmo que describe dos fuerzas opuestas y complementarias", "Un plato de comida china", "Un estilo de artes marciales"], correct:1},
  {text:"¿En qué país se celebra el festival de 'Holi'?", options:["Nepal", "Sri Lanka", "India", "Bangladés"], correct:2},
  {text:"¿Qué es un 'dólar de arena'?", options:["Una moneda antigua", "Un tipo de erizo de mar plano y excavador", "Una formación rocosa en el desierto", "Un pez del desierto"], correct:1},
  {text:"¿Cuál es el nombre del famoso museo de arte en Madrid?", options:["Museo del Louvre", "Museo Británico", "Museo del Prado", "Rijksmuseum"], correct:2},
  {text:"¿Qué es un 'fiordo'?", options:["Una montaña alta", "Una entrada de mar estrecha y profunda entre altas montañas", "Un lago glaciar", "Un desierto helado"], correct:1},
  {text:"¿Cuál es la capital de Islandia?", options:["Oslo", "Reikiavik", "Helsinki", "Dublín"], correct:1},
  {text:"¿Qué es la 'ceremonia del té' en Japón?", options:["Simplemente beber té", "Un ritual coreografiado de preparar y servir té verde", "Un festival de la cosecha del té", "Una forma de leer el futuro en las hojas de té"], correct:1},
  {text:"¿Quién fue el primer emperador de China?", options:["Confucio", "Sun Tzu", "Qin Shi Huang", "Kublai Khan"], correct:2},
  {text:"¿Qué es un 'bagel'?", options:["Un tipo de donut", "Un panecillo tradicionalmente hecho de masa de trigo, con un agujero en el centro", "Un pastel de queso", "Una galleta salada"], correct:1},
  {text:"¿Cuál es la montaña más alta de América del Norte?", options:["Monte Logan", "Pico de Orizaba", "Monte Denali", "Monte Whitney"], correct:2},
  {text:"¿Qué es el 'karma'?", options:["El destino", "La suerte", "Un concepto espiritual sobre la suma de las acciones de una persona y sus consecuencias", "La reencarnación"], correct:2},
  {text:"¿Qué es un 'castillo de naipes'?", options:["Un castillo real hecho de piedra", "Una estructura inestable creada apilando naipes", "Un tipo de juego de cartas", "Una fortaleza en un acantilado"], correct:1},
  {text:"¿Quién es el dios del vino en la mitología griega?", options:["Apolo", "Hermes", "Dionisio", "Ares"], correct:2},
  {text:"¿Cuál es la capital de Kenia?", options:["Lagos", "Adís Abeba", "Nairobi", "Dar es-Salam"], correct:2},
  {text:"¿Qué es la 'salsa Tabasco'?", options:["Una salsa de tomate mexicana", "Una marca de salsa picante estadounidense", "Una salsa de soja tailandesa", "Una salsa de barbacoa"], correct:1},
  {text:"¿Qué es el 'alfabeto cirílico'?", options:["El alfabeto utilizado para escribir griego", "Un sistema de escritura utilizado para varias lenguas eslavas", "El alfabeto hebreo", "El alfabeto árabe"], correct:1},
  {text:"¿Qué es un 'sombrero'?", options:["Un tipo de taco", "Un sombrero de ala ancha, tradicional de México", "Una bebida mexicana", "Un baile folclórico"], correct:1},
  {text:"¿Cuál es el nombre del río que atraviesa El Cairo?", options:["Tigris", "Éufrates", "Jordán", "Nilo"], correct:3},
  {text:"¿Qué es el 'flamenco'?", options:["Un ave zancuda rosa", "Un género de música y danza originario de Andalucía, España", "Un tipo de guitarra", "Ambas, el ave y el género musical"], correct:3},
  {text:"¿Quién fue Marco Polo?", options:["Un emperador romano", "Un filósofo griego", "Un mercader y explorador veneciano que viajó a Asia", "Un conquistador español"], correct:2},
  {text:"¿Cuál es el animal sagrado en el hinduismo?", options:["El elefante", "El mono", "La vaca", "La serpiente"], correct:2},
  {text:"¿Qué es un 'géiser'?", options:["Un volcán de lodo", "Una fuente termal que entra en erupción periódicamente", "Una cueva subterránea", "Una formación rocosa"], correct:1},
  {text:"¿En qué ciudad se encuentra la 'Puerta de Brandeburgo'?", options:["Viena", "Múnich", "Berlín", "Hamburgo"], correct:2},
  {text:"¿Quién escribió 'El Conde de Montecristo'?", options:["Victor Hugo", "Émile Zola", "Jules Verne", "Alexandre Dumas"], correct:3},
  {text:"¿Qué es la 'diáspora'?", options:["Una festividad religiosa", "La dispersión de un grupo de personas de su tierra natal", "Un tipo de gobierno", "Un acuerdo comercial"], correct:1},
  {text:"¿Cuál es la capital de Polonia?", options:["Cracovia", "Varsovia", "Gdansk", "Poznan"], correct:1},
  {text:"¿Qué es un 'koan' en el budismo zen?", options:["Una forma de meditación", "Un maestro zen", "Una historia o pregunta paradójica utilizada para la meditación", "Un templo zen"], correct:2},
  {text:"¿Qué es el 'Mardi Gras'?", options:["Un festival de la cosecha", "Las celebraciones de carnaval, especialmente en Nueva Orleans", "Un día de ayuno religioso", "Un mercado de Navidad"], correct:1}
];
