const questions = [
{text:"¿Capital de Francia?", options:["Roma","París","Madrid","Lisboa"], correct:1},
{text:"¿Planeta más grande?", options:["Marte","Venus","Júpiter","Tierra"], correct:2},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
{text:"¿Quién pintó la Mona Lisa?", options:['Picasso', 'Leonardo da Vinci', 'Van Gogh', 'Dalí'], correct:1},
{text:"¿Qué gas respiramos principalmente?", options:['Oxígeno', 'Nitrógeno', 'Dióxido de Carbono', 'Hidrógeno'], correct:1},
{text:"¿Cuántos continentes hay?", options:['5', '6', '7', '8'], correct:2},
{text:"¿En qué país están las pirámides de Giza?", options:['México', 'Egipto', 'Perú', 'India'], correct:1},
{text:"¿Cuál es el océano más grande?", options:['Atlántico', 'Pacífico', 'Índico', 'Ártico'], correct:1},
];