const questions = [
{text:"¿En qué año comenzó la Primera Guerra Mundial?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿Qué planeta es conocido como el planeta anillado?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"¿Qué país ganó el mundial de fútbol en 1998?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"Capital de Egipto", options:['Roma', 'París', 'Madrid', 'Lisboa'], correct:1},
{text:"¿Qué instrumento musical tiene viento?", options:['Guitarra', 'Piano', 'Violín', 'Flauta'], correct:1},
{text:"¿Qué país ganó el mundial de fútbol en 1998?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿Qué instrumento musical tiene teclas?", options:['Guitarra', 'Piano', 'Violín', 'Flauta'], correct:1},
{text:"Capital de México", options:['Roma', 'París', 'Madrid', 'Lisboa'], correct:1},
{text:"¿En qué año comenzó el fin de la Segunda Guerra Mundial?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿Quién escribió Hamlet?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"¿Qué instrumento musical tiene teclas?", options:['Guitarra', 'Piano', 'Violín', 'Flauta'], correct:1},
{text:"¿Qué país ganó el mundial de fútbol en 2018?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿Quién escribió Hamlet?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"¿Qué planeta es conocido como el planeta gigante?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"¿Qué planeta es conocido como el planeta gigante?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"¿Qué planeta es conocido como el planeta rojo?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"Capital de Argentina", options:['Roma', 'París', 'Madrid', 'Lisboa'], correct:1},
{text:"Capital de España", options:['Roma', 'París', 'Madrid', 'Lisboa'], correct:1},
{text:"Capital de Canadá", options:['Roma', 'París', 'Madrid', 'Lisboa'], correct:1},
{text:"¿Qué instrumento musical tiene teclas?", options:['Guitarra', 'Piano', 'Violín', 'Flauta'], correct:1},
{text:"¿Quién escribió Cien Años de Soledad?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"¿En qué año comenzó el Descubrimiento de América?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿Quién escribió Don Quijote?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"¿Qué país ganó el mundial de fútbol en 2018?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿Cuál es la montaña más alta del mundo?", options:['Everest', 'K2', 'Aconcagua', 'Kilimanjaro'], correct:0},
{text:"¿Qué país ganó el mundial de fútbol en 1970?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿En qué continente está Italia?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"¿En qué continente está Japón?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"¿Qué país ganó el mundial de fútbol en 1998?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿En qué año comenzó el Descubrimiento de América?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿Quién escribió Hamlet?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"¿Qué país ganó el mundial de fútbol en 1998?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿Cuál es la montaña más alta del mundo?", options:['Everest', 'K2', 'Aconcagua', 'Kilimanjaro'], correct:0},
{text:"¿En qué año comenzó la Primera Guerra Mundial?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿En qué continente está Italia?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"¿En qué continente está Francia?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"¿Cuál es el elemento químico con símbolo H?", options:['Hidrógeno', 'Oxígeno', 'Carbono', 'Helio'], correct:2},
{text:"¿Qué instrumento musical tiene viento?", options:['Guitarra', 'Piano', 'Violín', 'Flauta'], correct:1},
{text:"¿Cuál es el animal más grande?", options:['Elefante', 'Ballena Azul', 'Tiburón', 'Águila'], correct:1},
{text:"¿Quién escribió La Odisea?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"¿Qué país ganó el mundial de fútbol en 1998?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿En qué año comenzó la Independencia de Estados Unidos?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿En qué año comenzó la Independencia de Estados Unidos?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿Cuál es la montaña más alta del mundo?", options:['Everest', 'K2', 'Aconcagua', 'Kilimanjaro'], correct:0},
{text:"¿Qué instrumento musical tiene viento?", options:['Guitarra', 'Piano', 'Violín', 'Flauta'], correct:1},
{text:"¿Cuál es el elemento químico con símbolo O?", options:['Hidrógeno', 'Oxígeno', 'Carbono', 'Helio'], correct:2},
{text:"¿Cuál es el animal más alto?", options:['Elefante', 'Ballena Azul', 'Tiburón', 'Águila'], correct:1},
{text:"¿Cuál es el animal más pesado?", options:['Elefante', 'Ballena Azul', 'Tiburón', 'Águila'], correct:1},
{text:"¿Quién escribió Don Quijote?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"¿En qué año comenzó la Independencia de Estados Unidos?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿En qué continente está Canadá?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"¿Quién escribió Cien Años de Soledad?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"¿En qué año comenzó la Independencia de Estados Unidos?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿En qué continente está España?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"¿Cuál es el elemento químico con símbolo He?", options:['Hidrógeno', 'Oxígeno', 'Carbono', 'Helio'], correct:2},
{text:"¿En qué año comenzó la Independencia de Estados Unidos?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿Cuál es la montaña más alta del mundo?", options:['Everest', 'K2', 'Aconcagua', 'Kilimanjaro'], correct:0},
{text:"¿En qué continente está España?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"Capital de Canadá", options:['Roma', 'París', 'Madrid', 'Lisboa'], correct:1},
{text:"¿Qué planeta es conocido como el planeta rojo?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"¿Cuál es el elemento químico con símbolo O?", options:['Hidrógeno', 'Oxígeno', 'Carbono', 'Helio'], correct:2},
{text:"¿Cuál es la montaña más alta del mundo?", options:['Everest', 'K2', 'Aconcagua', 'Kilimanjaro'], correct:0},
{text:"¿Qué país ganó el mundial de fútbol en 1998?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿Qué instrumento musical tiene teclas?", options:['Guitarra', 'Piano', 'Violín', 'Flauta'], correct:1},
{text:"¿Cuál es la montaña más alta del mundo?", options:['Everest', 'K2', 'Aconcagua', 'Kilimanjaro'], correct:0},
{text:"¿En qué continente está México?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"¿En qué año comenzó la Independencia de Estados Unidos?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿Quién escribió La Odisea?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"¿Qué instrumento musical tiene cuerdas?", options:['Guitarra', 'Piano', 'Violín', 'Flauta'], correct:1},
{text:"¿Quién escribió Hamlet?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"Capital de Canadá", options:['Roma', 'París', 'Madrid', 'Lisboa'], correct:1},
{text:"¿Qué planeta es conocido como el planeta anillado?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"¿En qué continente está Francia?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"¿Qué país ganó el mundial de fútbol en 1970?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"Capital de Francia", options:['Roma', 'París', 'Madrid', 'Lisboa'], correct:1},
{text:"¿Cuál es la montaña más alta del mundo?", options:['Everest', 'K2', 'Aconcagua', 'Kilimanjaro'], correct:0},
{text:"¿Qué país ganó el mundial de fútbol en 1958?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿Cuál es el elemento químico con símbolo He?", options:['Hidrógeno', 'Oxígeno', 'Carbono', 'Helio'], correct:2},
{text:"¿Cuál es el elemento químico con símbolo H?", options:['Hidrógeno', 'Oxígeno', 'Carbono', 'Helio'], correct:2},
{text:"¿En qué año comenzó el Descubrimiento de América?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿Qué instrumento musical tiene arco?", options:['Guitarra', 'Piano', 'Violín', 'Flauta'], correct:1},
{text:"¿Qué planeta es conocido como el planeta rojo?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"¿Quién escribió Don Quijote?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"¿Qué país ganó el mundial de fútbol en 1998?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿Qué planeta es conocido como el planeta rojo?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"¿En qué continente está Egipto?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"¿Qué instrumento musical tiene viento?", options:['Guitarra', 'Piano', 'Violín', 'Flauta'], correct:1},
{text:"Capital de Egipto", options:['Roma', 'París', 'Madrid', 'Lisboa'], correct:1},
{text:"¿Qué instrumento musical tiene cuerdas?", options:['Guitarra', 'Piano', 'Violín', 'Flauta'], correct:1},
{text:"¿En qué año comenzó el Descubrimiento de América?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿Qué instrumento musical tiene viento?", options:['Guitarra', 'Piano', 'Violín', 'Flauta'], correct:1},
{text:"¿En qué año comenzó el Descubrimiento de América?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿Cuál es el animal más rápido?", options:['Elefante', 'Ballena Azul', 'Tiburón', 'Águila'], correct:1},
{text:"¿Qué planeta es conocido como el planeta rojo?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"¿Qué instrumento musical tiene teclas?", options:['Guitarra', 'Piano', 'Violín', 'Flauta'], correct:1},
{text:"¿Quién escribió Don Quijote?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"¿En qué continente está Italia?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"¿Cuál es la montaña más alta del mundo?", options:['Everest', 'K2', 'Aconcagua', 'Kilimanjaro'], correct:0},
{text:"¿Cuál es el elemento químico con símbolo H?", options:['Hidrógeno', 'Oxígeno', 'Carbono', 'Helio'], correct:2},
{text:"¿Cuál es el elemento químico con símbolo C?", options:['Hidrógeno', 'Oxígeno', 'Carbono', 'Helio'], correct:2},
{text:"¿Quién escribió Hamlet?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"¿Qué país ganó el mundial de fútbol en 1958?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿Cuál es el elemento químico con símbolo He?", options:['Hidrógeno', 'Oxígeno', 'Carbono', 'Helio'], correct:2},
{text:"¿Cuál es el elemento químico con símbolo H?", options:['Hidrógeno', 'Oxígeno', 'Carbono', 'Helio'], correct:2},
{text:"¿Qué país ganó el mundial de fútbol en 1998?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿Qué país ganó el mundial de fútbol en 1958?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿Cuál es la montaña más alta del mundo?", options:['Everest', 'K2', 'Aconcagua', 'Kilimanjaro'], correct:0},
{text:"¿Quién escribió Don Quijote?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"Capital de China", options:['Roma', 'París', 'Madrid', 'Lisboa'], correct:1},
{text:"¿Cuál es el elemento químico con símbolo O?", options:['Hidrógeno', 'Oxígeno', 'Carbono', 'Helio'], correct:2},
{text:"¿En qué continente está Chile?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"¿Cuál es la montaña más alta del mundo?", options:['Everest', 'K2', 'Aconcagua', 'Kilimanjaro'], correct:0},
{text:"¿Cuál es el animal más rápido?", options:['Elefante', 'Ballena Azul', 'Tiburón', 'Águila'], correct:1},
{text:"¿Cuál es la montaña más alta del mundo?", options:['Everest', 'K2', 'Aconcagua', 'Kilimanjaro'], correct:0},
{text:"¿Qué país ganó el mundial de fútbol en 2018?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿Qué país ganó el mundial de fútbol en 1970?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿En qué año comenzó la Independencia de Estados Unidos?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿Quién escribió Don Quijote?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"¿En qué continente está España?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"¿En qué continente está Canadá?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"¿Qué país ganó el mundial de fútbol en 1998?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿Quién escribió Hamlet?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"¿En qué año comenzó la Primera Guerra Mundial?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿Cuál es el elemento químico con símbolo C?", options:['Hidrógeno', 'Oxígeno', 'Carbono', 'Helio'], correct:2},
{text:"¿Qué país ganó el mundial de fútbol en 2018?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿Qué instrumento musical tiene viento?", options:['Guitarra', 'Piano', 'Violín', 'Flauta'], correct:1},
{text:"¿Qué instrumento musical tiene arco?", options:['Guitarra', 'Piano', 'Violín', 'Flauta'], correct:1},
{text:"¿En qué continente está Chile?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"¿Cuál es la montaña más alta del mundo?", options:['Everest', 'K2', 'Aconcagua', 'Kilimanjaro'], correct:0},
{text:"Capital de Argentina", options:['Roma', 'París', 'Madrid', 'Lisboa'], correct:1},
{text:"¿Qué instrumento musical tiene viento?", options:['Guitarra', 'Piano', 'Violín', 'Flauta'], correct:1},
{text:"¿Cuál es la montaña más alta del mundo?", options:['Everest', 'K2', 'Aconcagua', 'Kilimanjaro'], correct:0},
{text:"¿En qué año comenzó la Primera Guerra Mundial?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿Qué país ganó el mundial de fútbol en 1998?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿Qué instrumento musical tiene cuerdas?", options:['Guitarra', 'Piano', 'Violín', 'Flauta'], correct:1},
{text:"¿En qué año comenzó el fin de la Segunda Guerra Mundial?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿Cuál es el animal más pesado?", options:['Elefante', 'Ballena Azul', 'Tiburón', 'Águila'], correct:1},
{text:"¿Cuál es el elemento químico con símbolo He?", options:['Hidrógeno', 'Oxígeno', 'Carbono', 'Helio'], correct:2},
{text:"¿Cuál es el animal más pesado?", options:['Elefante', 'Ballena Azul', 'Tiburón', 'Águila'], correct:1},
{text:"¿Quién escribió La Odisea?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"¿Cuál es la montaña más alta del mundo?", options:['Everest', 'K2', 'Aconcagua', 'Kilimanjaro'], correct:0},
{text:"¿En qué año comenzó la Primera Guerra Mundial?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿Cuál es el animal más grande?", options:['Elefante', 'Ballena Azul', 'Tiburón', 'Águila'], correct:1},
{text:"¿Qué planeta es conocido como el planeta gemelo de la Tierra?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"Capital de Canadá", options:['Roma', 'París', 'Madrid', 'Lisboa'], correct:1},
{text:"¿Cuál es el elemento químico con símbolo He?", options:['Hidrógeno', 'Oxígeno', 'Carbono', 'Helio'], correct:2},
{text:"Capital de Italia", options:['Roma', 'París', 'Madrid', 'Lisboa'], correct:1},
{text:"¿Cuál es el animal más grande?", options:['Elefante', 'Ballena Azul', 'Tiburón', 'Águila'], correct:1},
{text:"¿Qué instrumento musical tiene cuerdas?", options:['Guitarra', 'Piano', 'Violín', 'Flauta'], correct:1},
{text:"¿En qué continente está México?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"¿Quién escribió Don Quijote?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"¿En qué continente está Egipto?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"¿Qué instrumento musical tiene teclas?", options:['Guitarra', 'Piano', 'Violín', 'Flauta'], correct:1},
{text:"¿Qué instrumento musical tiene arco?", options:['Guitarra', 'Piano', 'Violín', 'Flauta'], correct:1},
{text:"¿Cuál es el elemento químico con símbolo He?", options:['Hidrógeno', 'Oxígeno', 'Carbono', 'Helio'], correct:2},
{text:"¿Cuál es el elemento químico con símbolo H?", options:['Hidrógeno', 'Oxígeno', 'Carbono', 'Helio'], correct:2},
{text:"¿En qué continente está Italia?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"¿Qué planeta es conocido como el planeta gemelo de la Tierra?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"¿En qué año comenzó el Descubrimiento de América?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿Quién escribió Don Quijote?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"¿En qué continente está Chile?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"¿Qué país ganó el mundial de fútbol en 2018?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿Cuál es el animal más pesado?", options:['Elefante', 'Ballena Azul', 'Tiburón', 'Águila'], correct:1},
{text:"¿Qué país ganó el mundial de fútbol en 1958?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"Capital de Chile", options:['Roma', 'París', 'Madrid', 'Lisboa'], correct:1},
{text:"¿Qué instrumento musical tiene arco?", options:['Guitarra', 'Piano', 'Violín', 'Flauta'], correct:1},
{text:"¿En qué año comenzó el fin de la Segunda Guerra Mundial?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿Qué país ganó el mundial de fútbol en 1970?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿Qué planeta es conocido como el planeta gigante?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"¿Cuál es la montaña más alta del mundo?", options:['Everest', 'K2', 'Aconcagua', 'Kilimanjaro'], correct:0},
{text:"¿Cuál es el elemento químico con símbolo H?", options:['Hidrógeno', 'Oxígeno', 'Carbono', 'Helio'], correct:2},
{text:"¿Cuál es la montaña más alta del mundo?", options:['Everest', 'K2', 'Aconcagua', 'Kilimanjaro'], correct:0},
{text:"¿En qué continente está China?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"Capital de Canadá", options:['Roma', 'París', 'Madrid', 'Lisboa'], correct:1},
{text:"¿Cuál es el elemento químico con símbolo C?", options:['Hidrógeno', 'Oxígeno', 'Carbono', 'Helio'], correct:2},
{text:"¿Qué país ganó el mundial de fútbol en 2018?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿Qué país ganó el mundial de fútbol en 1998?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿En qué año comenzó la Primera Guerra Mundial?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿Quién escribió Hamlet?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"¿Qué país ganó el mundial de fútbol en 1970?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿Quién escribió Don Quijote?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"¿Cuál es el elemento químico con símbolo C?", options:['Hidrógeno', 'Oxígeno', 'Carbono', 'Helio'], correct:2},
{text:"¿Quién escribió Cien Años de Soledad?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"¿Qué planeta es conocido como el planeta gemelo de la Tierra?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"¿Qué planeta es conocido como el planeta rojo?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"¿Qué planeta es conocido como el planeta rojo?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"¿Cuál es el animal más rápido?", options:['Elefante', 'Ballena Azul', 'Tiburón', 'Águila'], correct:1},
{text:"¿Qué país ganó el mundial de fútbol en 1958?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"Capital de China", options:['Roma', 'París', 'Madrid', 'Lisboa'], correct:1},
{text:"¿En qué año comenzó el Descubrimiento de América?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿Qué país ganó el mundial de fútbol en 2018?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"Capital de Francia", options:['Roma', 'París', 'Madrid', 'Lisboa'], correct:1},
{text:"¿Cuál es el animal más pesado?", options:['Elefante', 'Ballena Azul', 'Tiburón', 'Águila'], correct:1},
{text:"¿Qué país ganó el mundial de fútbol en 1958?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿Cuál es el elemento químico con símbolo O?", options:['Hidrógeno', 'Oxígeno', 'Carbono', 'Helio'], correct:2},
{text:"¿Cuál es la montaña más alta del mundo?", options:['Everest', 'K2', 'Aconcagua', 'Kilimanjaro'], correct:0},
{text:"¿Quién escribió Don Quijote?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"¿Quién escribió Hamlet?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"¿En qué año comenzó el Descubrimiento de América?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿Cuál es la montaña más alta del mundo?", options:['Everest', 'K2', 'Aconcagua', 'Kilimanjaro'], correct:0},
{text:"¿Qué planeta es conocido como el planeta gigante?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"¿Cuál es la montaña más alta del mundo?", options:['Everest', 'K2', 'Aconcagua', 'Kilimanjaro'], correct:0},
{text:"¿En qué año comenzó el Descubrimiento de América?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿Cuál es el elemento químico con símbolo H?", options:['Hidrógeno', 'Oxígeno', 'Carbono', 'Helio'], correct:2},
{text:"Capital de Japón", options:['Roma', 'París', 'Madrid', 'Lisboa'], correct:1},
{text:"¿Qué planeta es conocido como el planeta gigante?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"¿En qué año comenzó la Independencia de Estados Unidos?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿En qué año comenzó el Descubrimiento de América?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"Capital de Canadá", options:['Roma', 'París', 'Madrid', 'Lisboa'], correct:1},
{text:"¿Qué país ganó el mundial de fútbol en 1958?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿Qué planeta es conocido como el planeta rojo?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"¿Cuál es el animal más grande?", options:['Elefante', 'Ballena Azul', 'Tiburón', 'Águila'], correct:1},
{text:"¿Cuál es el animal más pesado?", options:['Elefante', 'Ballena Azul', 'Tiburón', 'Águila'], correct:1},
{text:"¿Quién escribió Hamlet?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"¿Cuál es el elemento químico con símbolo C?", options:['Hidrógeno', 'Oxígeno', 'Carbono', 'Helio'], correct:2},
{text:"¿Cuál es el animal más grande?", options:['Elefante', 'Ballena Azul', 'Tiburón', 'Águila'], correct:1},
{text:"¿Qué país ganó el mundial de fútbol en 1998?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿Qué planeta es conocido como el planeta anillado?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"¿En qué continente está Italia?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"¿Qué instrumento musical tiene cuerdas?", options:['Guitarra', 'Piano', 'Violín', 'Flauta'], correct:1},
{text:"¿Cuál es el elemento químico con símbolo H?", options:['Hidrógeno', 'Oxígeno', 'Carbono', 'Helio'], correct:2},
{text:"¿Qué planeta es conocido como el planeta rojo?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"¿Cuál es el elemento químico con símbolo He?", options:['Hidrógeno', 'Oxígeno', 'Carbono', 'Helio'], correct:2},
{text:"¿Cuál es la montaña más alta del mundo?", options:['Everest', 'K2', 'Aconcagua', 'Kilimanjaro'], correct:0},
{text:"Capital de Japón", options:['Roma', 'París', 'Madrid', 'Lisboa'], correct:1},
{text:"¿En qué continente está Canadá?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"¿Qué país ganó el mundial de fútbol en 2018?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿Cuál es la montaña más alta del mundo?", options:['Everest', 'K2', 'Aconcagua', 'Kilimanjaro'], correct:0},
{text:"¿Qué planeta es conocido como el planeta rojo?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"¿Qué país ganó el mundial de fútbol en 2018?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿Quién escribió Cien Años de Soledad?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"¿En qué año comenzó el Descubrimiento de América?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿Qué instrumento musical tiene viento?", options:['Guitarra', 'Piano', 'Violín', 'Flauta'], correct:1},
{text:"¿Qué planeta es conocido como el planeta anillado?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"¿En qué año comenzó el Descubrimiento de América?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿Cuál es el animal más rápido?", options:['Elefante', 'Ballena Azul', 'Tiburón', 'Águila'], correct:1},
{text:"¿En qué continente está España?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"¿Cuál es el elemento químico con símbolo C?", options:['Hidrógeno', 'Oxígeno', 'Carbono', 'Helio'], correct:2},
{text:"¿Cuál es la montaña más alta del mundo?", options:['Everest', 'K2', 'Aconcagua', 'Kilimanjaro'], correct:0},
{text:"¿Qué planeta es conocido como el planeta gemelo de la Tierra?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"Capital de China", options:['Roma', 'París', 'Madrid', 'Lisboa'], correct:1},
{text:"¿Quién escribió Don Quijote?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"¿Qué instrumento musical tiene arco?", options:['Guitarra', 'Piano', 'Violín', 'Flauta'], correct:1},
{text:"¿Qué país ganó el mundial de fútbol en 1998?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿En qué año comenzó la Primera Guerra Mundial?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿En qué año comenzó la Independencia de Estados Unidos?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿Qué país ganó el mundial de fútbol en 1998?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿Qué planeta es conocido como el planeta anillado?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"¿Qué país ganó el mundial de fútbol en 1970?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿En qué año comenzó el fin de la Segunda Guerra Mundial?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿En qué continente está México?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"¿Quién escribió Hamlet?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"¿En qué año comenzó el Descubrimiento de América?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"Capital de Egipto", options:['Roma', 'París', 'Madrid', 'Lisboa'], correct:1},
{text:"¿Cuál es el animal más alto?", options:['Elefante', 'Ballena Azul', 'Tiburón', 'Águila'], correct:1},
{text:"¿Qué país ganó el mundial de fútbol en 1970?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿Qué instrumento musical tiene cuerdas?", options:['Guitarra', 'Piano', 'Violín', 'Flauta'], correct:1},
{text:"¿Qué planeta es conocido como el planeta gemelo de la Tierra?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"¿En qué año comenzó la Primera Guerra Mundial?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿En qué continente está Canadá?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"¿Cuál es la montaña más alta del mundo?", options:['Everest', 'K2', 'Aconcagua', 'Kilimanjaro'], correct:0},
{text:"¿Qué país ganó el mundial de fútbol en 1970?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿En qué año comenzó el fin de la Segunda Guerra Mundial?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿En qué continente está Chile?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"¿Quién escribió La Odisea?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"Capital de Japón", options:['Roma', 'París', 'Madrid', 'Lisboa'], correct:1},
{text:"¿Cuál es el animal más pesado?", options:['Elefante', 'Ballena Azul', 'Tiburón', 'Águila'], correct:1},
{text:"¿En qué continente está España?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"¿Cuál es la montaña más alta del mundo?", options:['Everest', 'K2', 'Aconcagua', 'Kilimanjaro'], correct:0},
{text:"¿Cuál es la montaña más alta del mundo?", options:['Everest', 'K2', 'Aconcagua', 'Kilimanjaro'], correct:0},
{text:"¿Qué instrumento musical tiene teclas?", options:['Guitarra', 'Piano', 'Violín', 'Flauta'], correct:1},
{text:"¿Qué planeta es conocido como el planeta gemelo de la Tierra?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"¿Quién escribió Cien Años de Soledad?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"¿Cuál es la montaña más alta del mundo?", options:['Everest', 'K2', 'Aconcagua', 'Kilimanjaro'], correct:0},
{text:"¿Qué país ganó el mundial de fútbol en 1998?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿Cuál es el animal más grande?", options:['Elefante', 'Ballena Azul', 'Tiburón', 'Águila'], correct:1},
{text:"¿Cuál es la montaña más alta del mundo?", options:['Everest', 'K2', 'Aconcagua', 'Kilimanjaro'], correct:0},
{text:"¿Qué país ganó el mundial de fútbol en 1958?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿En qué año comenzó la Independencia de Estados Unidos?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿En qué continente está Egipto?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"¿En qué continente está Italia?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"¿Qué planeta es conocido como el planeta gigante?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"¿Qué país ganó el mundial de fútbol en 1958?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿Quién escribió La Odisea?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"¿Cuál es el elemento químico con símbolo He?", options:['Hidrógeno', 'Oxígeno', 'Carbono', 'Helio'], correct:2},
{text:"¿Qué país ganó el mundial de fútbol en 1998?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿Qué país ganó el mundial de fútbol en 1970?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿Qué planeta es conocido como el planeta rojo?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"¿Cuál es el animal más alto?", options:['Elefante', 'Ballena Azul', 'Tiburón', 'Águila'], correct:1},
{text:"¿En qué continente está Japón?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"¿Cuál es el elemento químico con símbolo H?", options:['Hidrógeno', 'Oxígeno', 'Carbono', 'Helio'], correct:2},
{text:"¿Quién escribió Don Quijote?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"Capital de Francia", options:['Roma', 'París', 'Madrid', 'Lisboa'], correct:1},
{text:"¿Cuál es el elemento químico con símbolo He?", options:['Hidrógeno', 'Oxígeno', 'Carbono', 'Helio'], correct:2},
{text:"¿Qué instrumento musical tiene arco?", options:['Guitarra', 'Piano', 'Violín', 'Flauta'], correct:1},
{text:"¿En qué año comenzó la Independencia de Estados Unidos?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿En qué continente está Egipto?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"¿Cuál es la montaña más alta del mundo?", options:['Everest', 'K2', 'Aconcagua', 'Kilimanjaro'], correct:0},
{text:"¿Qué planeta es conocido como el planeta rojo?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"¿Qué planeta es conocido como el planeta gigante?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"¿En qué año comenzó la Independencia de Estados Unidos?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿Quién escribió Don Quijote?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"¿Quién escribió Don Quijote?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"¿En qué año comenzó el fin de la Segunda Guerra Mundial?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿Quién escribió La Odisea?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"¿Cuál es la montaña más alta del mundo?", options:['Everest', 'K2', 'Aconcagua', 'Kilimanjaro'], correct:0},
{text:"¿Qué planeta es conocido como el planeta rojo?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"¿Cuál es el animal más pesado?", options:['Elefante', 'Ballena Azul', 'Tiburón', 'Águila'], correct:1},
{text:"¿Quién escribió Don Quijote?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"¿Qué planeta es conocido como el planeta gigante?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"¿En qué año comenzó la Primera Guerra Mundial?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿En qué continente está Francia?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"¿Cuál es el animal más alto?", options:['Elefante', 'Ballena Azul', 'Tiburón', 'Águila'], correct:1},
{text:"¿Cuál es la montaña más alta del mundo?", options:['Everest', 'K2', 'Aconcagua', 'Kilimanjaro'], correct:0},
{text:"¿En qué año comenzó el Descubrimiento de América?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿En qué año comenzó el fin de la Segunda Guerra Mundial?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿Qué país ganó el mundial de fútbol en 1970?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿Quién escribió Don Quijote?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"¿Qué instrumento musical tiene viento?", options:['Guitarra', 'Piano', 'Violín', 'Flauta'], correct:1},
{text:"¿Qué instrumento musical tiene teclas?", options:['Guitarra', 'Piano', 'Violín', 'Flauta'], correct:1},
{text:"¿Quién escribió Cien Años de Soledad?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"¿Qué instrumento musical tiene teclas?", options:['Guitarra', 'Piano', 'Violín', 'Flauta'], correct:1},
{text:"¿Cuál es la montaña más alta del mundo?", options:['Everest', 'K2', 'Aconcagua', 'Kilimanjaro'], correct:0},
{text:"¿Cuál es el elemento químico con símbolo H?", options:['Hidrógeno', 'Oxígeno', 'Carbono', 'Helio'], correct:2},
{text:"¿Qué planeta es conocido como el planeta rojo?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"¿Qué instrumento musical tiene viento?", options:['Guitarra', 'Piano', 'Violín', 'Flauta'], correct:1},
{text:"¿Quién escribió Don Quijote?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"¿En qué continente está México?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"¿En qué año comenzó la Independencia de Estados Unidos?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿Qué país ganó el mundial de fútbol en 1958?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿Qué instrumento musical tiene arco?", options:['Guitarra', 'Piano', 'Violín', 'Flauta'], correct:1},
{text:"¿Quién escribió Cien Años de Soledad?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"¿Qué planeta es conocido como el planeta gemelo de la Tierra?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"¿Qué planeta es conocido como el planeta rojo?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"¿Cuál es el elemento químico con símbolo C?", options:['Hidrógeno', 'Oxígeno', 'Carbono', 'Helio'], correct:2},
{text:"Capital de Italia", options:['Roma', 'París', 'Madrid', 'Lisboa'], correct:1},
{text:"Capital de Francia", options:['Roma', 'París', 'Madrid', 'Lisboa'], correct:1},
{text:"¿Qué planeta es conocido como el planeta rojo?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"Capital de España", options:['Roma', 'París', 'Madrid', 'Lisboa'], correct:1},
{text:"¿Cuál es el elemento químico con símbolo O?", options:['Hidrógeno', 'Oxígeno', 'Carbono', 'Helio'], correct:2},
{text:"¿Cuál es el elemento químico con símbolo H?", options:['Hidrógeno', 'Oxígeno', 'Carbono', 'Helio'], correct:2},
{text:"Capital de México", options:['Roma', 'París', 'Madrid', 'Lisboa'], correct:1},
{text:"¿En qué continente está Italia?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"¿Cuál es el elemento químico con símbolo H?", options:['Hidrógeno', 'Oxígeno', 'Carbono', 'Helio'], correct:2},
{text:"¿Cuál es el animal más rápido?", options:['Elefante', 'Ballena Azul', 'Tiburón', 'Águila'], correct:1},
{text:"¿Qué instrumento musical tiene viento?", options:['Guitarra', 'Piano', 'Violín', 'Flauta'], correct:1},
{text:"¿Qué país ganó el mundial de fútbol en 1958?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿Quién escribió La Odisea?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"¿Cuál es el animal más pesado?", options:['Elefante', 'Ballena Azul', 'Tiburón', 'Águila'], correct:1},
{text:"¿En qué año comenzó el Descubrimiento de América?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"Capital de Francia", options:['Roma', 'París', 'Madrid', 'Lisboa'], correct:1},
{text:"¿En qué continente está México?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"¿Cuál es el elemento químico con símbolo H?", options:['Hidrógeno', 'Oxígeno', 'Carbono', 'Helio'], correct:2},
{text:"¿En qué continente está Japón?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"¿Cuál es la montaña más alta del mundo?", options:['Everest', 'K2', 'Aconcagua', 'Kilimanjaro'], correct:0},
{text:"¿Qué instrumento musical tiene cuerdas?", options:['Guitarra', 'Piano', 'Violín', 'Flauta'], correct:1},
{text:"¿Cuál es el elemento químico con símbolo H?", options:['Hidrógeno', 'Oxígeno', 'Carbono', 'Helio'], correct:2},
{text:"¿Qué planeta es conocido como el planeta gigante?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"¿Cuál es la montaña más alta del mundo?", options:['Everest', 'K2', 'Aconcagua', 'Kilimanjaro'], correct:0},
{text:"¿Quién escribió Hamlet?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"¿Qué planeta es conocido como el planeta anillado?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"Capital de España", options:['Roma', 'París', 'Madrid', 'Lisboa'], correct:1},
{text:"¿Qué país ganó el mundial de fútbol en 2018?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿Qué instrumento musical tiene cuerdas?", options:['Guitarra', 'Piano', 'Violín', 'Flauta'], correct:1},
{text:"¿En qué continente está Chile?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"¿En qué continente está Chile?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"¿Cuál es el animal más pesado?", options:['Elefante', 'Ballena Azul', 'Tiburón', 'Águila'], correct:1},
{text:"¿En qué año comenzó el fin de la Segunda Guerra Mundial?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿En qué continente está Japón?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"Capital de Argentina", options:['Roma', 'París', 'Madrid', 'Lisboa'], correct:1},
{text:"¿Qué instrumento musical tiene cuerdas?", options:['Guitarra', 'Piano', 'Violín', 'Flauta'], correct:1},
{text:"¿Cuál es la montaña más alta del mundo?", options:['Everest', 'K2', 'Aconcagua', 'Kilimanjaro'], correct:0},
{text:"Capital de España", options:['Roma', 'París', 'Madrid', 'Lisboa'], correct:1},
{text:"¿Qué instrumento musical tiene cuerdas?", options:['Guitarra', 'Piano', 'Violín', 'Flauta'], correct:1},
{text:"¿Cuál es la montaña más alta del mundo?", options:['Everest', 'K2', 'Aconcagua', 'Kilimanjaro'], correct:0},
{text:"¿Cuál es el animal más grande?", options:['Elefante', 'Ballena Azul', 'Tiburón', 'Águila'], correct:1},
{text:"¿Qué planeta es conocido como el planeta anillado?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"¿Qué país ganó el mundial de fútbol en 1958?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿Qué planeta es conocido como el planeta rojo?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"¿En qué año comenzó el Descubrimiento de América?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿Qué instrumento musical tiene teclas?", options:['Guitarra', 'Piano', 'Violín', 'Flauta'], correct:1},
{text:"¿Cuál es el elemento químico con símbolo He?", options:['Hidrógeno', 'Oxígeno', 'Carbono', 'Helio'], correct:2},
{text:"¿Cuál es la montaña más alta del mundo?", options:['Everest', 'K2', 'Aconcagua', 'Kilimanjaro'], correct:0},
{text:"¿En qué continente está Egipto?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"¿Qué planeta es conocido como el planeta rojo?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"¿En qué continente está Egipto?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"¿Cuál es el elemento químico con símbolo C?", options:['Hidrógeno', 'Oxígeno', 'Carbono', 'Helio'], correct:2},
{text:"¿Qué planeta es conocido como el planeta rojo?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"¿En qué continente está Italia?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"¿Cuál es la montaña más alta del mundo?", options:['Everest', 'K2', 'Aconcagua', 'Kilimanjaro'], correct:0},
{text:"¿Quién escribió Cien Años de Soledad?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"¿En qué continente está Chile?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"¿En qué continente está Argentina?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"¿Cuál es el elemento químico con símbolo C?", options:['Hidrógeno', 'Oxígeno', 'Carbono', 'Helio'], correct:2},
{text:"¿Cuál es la montaña más alta del mundo?", options:['Everest', 'K2', 'Aconcagua', 'Kilimanjaro'], correct:0},
{text:"Capital de Canadá", options:['Roma', 'París', 'Madrid', 'Lisboa'], correct:1},
{text:"¿En qué continente está España?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"¿Quién escribió La Odisea?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"¿Qué planeta es conocido como el planeta gigante?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"¿En qué año comenzó el fin de la Segunda Guerra Mundial?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿En qué continente está México?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"¿Qué país ganó el mundial de fútbol en 1970?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿Qué país ganó el mundial de fútbol en 1998?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿Qué país ganó el mundial de fútbol en 1998?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿En qué continente está Egipto?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"¿Cuál es el animal más rápido?", options:['Elefante', 'Ballena Azul', 'Tiburón', 'Águila'], correct:1},
{text:"¿En qué año comenzó la Primera Guerra Mundial?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿Cuál es la montaña más alta del mundo?", options:['Everest', 'K2', 'Aconcagua', 'Kilimanjaro'], correct:0},
{text:"¿Qué planeta es conocido como el planeta gigante?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"¿Qué país ganó el mundial de fútbol en 2018?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿En qué continente está México?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"¿Cuál es el elemento químico con símbolo He?", options:['Hidrógeno', 'Oxígeno', 'Carbono', 'Helio'], correct:2},
{text:"¿Cuál es el elemento químico con símbolo He?", options:['Hidrógeno', 'Oxígeno', 'Carbono', 'Helio'], correct:2},
{text:"¿Qué país ganó el mundial de fútbol en 2018?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿Quién escribió Cien Años de Soledad?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"¿Cuál es la montaña más alta del mundo?", options:['Everest', 'K2', 'Aconcagua', 'Kilimanjaro'], correct:0},
{text:"¿Qué instrumento musical tiene teclas?", options:['Guitarra', 'Piano', 'Violín', 'Flauta'], correct:1},
{text:"¿Qué instrumento musical tiene teclas?", options:['Guitarra', 'Piano', 'Violín', 'Flauta'], correct:1},
{text:"¿Cuál es el animal más rápido?", options:['Elefante', 'Ballena Azul', 'Tiburón', 'Águila'], correct:1},
{text:"¿Qué país ganó el mundial de fútbol en 1998?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿Cuál es el elemento químico con símbolo H?", options:['Hidrógeno', 'Oxígeno', 'Carbono', 'Helio'], correct:2},
{text:"¿Qué instrumento musical tiene arco?", options:['Guitarra', 'Piano', 'Violín', 'Flauta'], correct:1},
{text:"¿Qué planeta es conocido como el planeta gigante?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"¿Cuál es el elemento químico con símbolo He?", options:['Hidrógeno', 'Oxígeno', 'Carbono', 'Helio'], correct:2},
{text:"¿Cuál es el animal más pesado?", options:['Elefante', 'Ballena Azul', 'Tiburón', 'Águila'], correct:1},
{text:"¿Cuál es el elemento químico con símbolo H?", options:['Hidrógeno', 'Oxígeno', 'Carbono', 'Helio'], correct:2},
{text:"¿Cuál es el animal más alto?", options:['Elefante', 'Ballena Azul', 'Tiburón', 'Águila'], correct:1},
{text:"¿Quién escribió La Odisea?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"¿Cuál es la montaña más alta del mundo?", options:['Everest', 'K2', 'Aconcagua', 'Kilimanjaro'], correct:0},
{text:"¿Qué país ganó el mundial de fútbol en 1958?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿En qué año comenzó el fin de la Segunda Guerra Mundial?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿Qué instrumento musical tiene viento?", options:['Guitarra', 'Piano', 'Violín', 'Flauta'], correct:1},
{text:"Capital de Francia", options:['Roma', 'París', 'Madrid', 'Lisboa'], correct:1},
{text:"¿En qué año comenzó la Primera Guerra Mundial?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿Qué planeta es conocido como el planeta rojo?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"¿Qué país ganó el mundial de fútbol en 1998?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿En qué continente está Argentina?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"Capital de Egipto", options:['Roma', 'París', 'Madrid', 'Lisboa'], correct:1},
{text:"¿En qué año comenzó la Primera Guerra Mundial?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿Qué instrumento musical tiene arco?", options:['Guitarra', 'Piano', 'Violín', 'Flauta'], correct:1},
{text:"¿En qué año comenzó el Descubrimiento de América?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿Cuál es el elemento químico con símbolo H?", options:['Hidrógeno', 'Oxígeno', 'Carbono', 'Helio'], correct:2},
{text:"¿En qué continente está España?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"¿Quién escribió La Odisea?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"¿En qué año comenzó el Descubrimiento de América?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿Qué planeta es conocido como el planeta rojo?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"¿En qué año comenzó la Primera Guerra Mundial?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿En qué año comenzó el Descubrimiento de América?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿En qué año comenzó la Independencia de Estados Unidos?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿Cuál es la montaña más alta del mundo?", options:['Everest', 'K2', 'Aconcagua', 'Kilimanjaro'], correct:0},
{text:"¿Quién escribió Don Quijote?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"¿Qué instrumento musical tiene cuerdas?", options:['Guitarra', 'Piano', 'Violín', 'Flauta'], correct:1},
{text:"¿Qué instrumento musical tiene arco?", options:['Guitarra', 'Piano', 'Violín', 'Flauta'], correct:1},
{text:"¿En qué año comenzó el Descubrimiento de América?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿En qué año comenzó el Descubrimiento de América?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿Cuál es el animal más grande?", options:['Elefante', 'Ballena Azul', 'Tiburón', 'Águila'], correct:1},
{text:"¿Cuál es el animal más alto?", options:['Elefante', 'Ballena Azul', 'Tiburón', 'Águila'], correct:1},
{text:"¿Qué país ganó el mundial de fútbol en 2018?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿Qué instrumento musical tiene arco?", options:['Guitarra', 'Piano', 'Violín', 'Flauta'], correct:1},
{text:"¿Cuál es el elemento químico con símbolo O?", options:['Hidrógeno', 'Oxígeno', 'Carbono', 'Helio'], correct:2},
{text:"¿En qué continente está México?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"¿Qué planeta es conocido como el planeta gigante?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"¿Qué planeta es conocido como el planeta gemelo de la Tierra?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"¿Qué instrumento musical tiene viento?", options:['Guitarra', 'Piano', 'Violín', 'Flauta'], correct:1},
{text:"¿En qué continente está Japón?", options:['Europa', 'Asia', 'África', 'América'], correct:0},
{text:"¿Qué país ganó el mundial de fútbol en 1970?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿Qué instrumento musical tiene arco?", options:['Guitarra', 'Piano', 'Violín', 'Flauta'], correct:1},
{text:"¿Cuál es la montaña más alta del mundo?", options:['Everest', 'K2', 'Aconcagua', 'Kilimanjaro'], correct:0},
{text:"Capital de México", options:['Roma', 'París', 'Madrid', 'Lisboa'], correct:1},
{text:"Capital de Egipto", options:['Roma', 'París', 'Madrid', 'Lisboa'], correct:1},
{text:"¿Cuál es el animal más grande?", options:['Elefante', 'Ballena Azul', 'Tiburón', 'Águila'], correct:1},
{text:"¿Cuál es el animal más grande?", options:['Elefante', 'Ballena Azul', 'Tiburón', 'Águila'], correct:1},
{text:"¿En qué año comenzó el Descubrimiento de América?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿Cuál es el animal más alto?", options:['Elefante', 'Ballena Azul', 'Tiburón', 'Águila'], correct:1},
{text:"¿Quién escribió Don Quijote?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"Capital de Japón", options:['Roma', 'París', 'Madrid', 'Lisboa'], correct:1},
{text:"¿Cuál es la montaña más alta del mundo?", options:['Everest', 'K2', 'Aconcagua', 'Kilimanjaro'], correct:0},
{text:"¿En qué año comenzó el Descubrimiento de América?", options:['1492', '1776', '1914', '1945'], correct:0},
{text:"¿Qué país ganó el mundial de fútbol en 1970?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿Cuál es la montaña más alta del mundo?", options:['Everest', 'K2', 'Aconcagua', 'Kilimanjaro'], correct:0},
{text:"Capital de México", options:['Roma', 'París', 'Madrid', 'Lisboa'], correct:1},
{text:"¿Qué país ganó el mundial de fútbol en 1958?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿Qué planeta es conocido como el planeta rojo?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"¿Cuál es la montaña más alta del mundo?", options:['Everest', 'K2', 'Aconcagua', 'Kilimanjaro'], correct:0},
{text:"Capital de Chile", options:['Roma', 'París', 'Madrid', 'Lisboa'], correct:1},
{text:"¿Quién escribió Don Quijote?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"¿Qué país ganó el mundial de fútbol en 1970?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"¿Qué instrumento musical tiene arco?", options:['Guitarra', 'Piano', 'Violín', 'Flauta'], correct:1},
{text:"¿Cuál es el animal más alto?", options:['Elefante', 'Ballena Azul', 'Tiburón', 'Águila'], correct:1},
{text:"¿Cuál es la montaña más alta del mundo?", options:['Everest', 'K2', 'Aconcagua', 'Kilimanjaro'], correct:0},
{text:"Capital de Canadá", options:['Roma', 'París', 'Madrid', 'Lisboa'], correct:1},
{text:"¿Quién escribió Cien Años de Soledad?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"¿Qué planeta es conocido como el planeta gemelo de la Tierra?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"Capital de Italia", options:['Roma', 'París', 'Madrid', 'Lisboa'], correct:1},
{text:"¿Quién escribió Cien Años de Soledad?", options:['Cervantes', 'Shakespeare', 'Gabriel García Márquez', 'Homero'], correct:1},
{text:"¿Cuál es el animal más alto?", options:['Elefante', 'Ballena Azul', 'Tiburón', 'Águila'], correct:1},
{text:"¿Qué planeta es conocido como el planeta gigante?", options:['Marte', 'Júpiter', 'Venus', 'Saturno'], correct:0},
{text:"¿Qué país ganó el mundial de fútbol en 1958?", options:['Brasil', 'Alemania', 'Italia', 'Francia'], correct:0},
{text:"Capital de México", options:['Roma', 'París', 'Madrid', 'Lisboa'], correct:1},
{text:"Capital de Chile", options:['Roma', 'París', 'Madrid', 'Lisboa'], correct:1},
];
